apiVersion: v1
kind: Pod
metadata:
  name: trusted-bigdl-llm-serving-tdx-a1234bd-controller
  labels:
    fastchat-appid: a1234bd
    fastchat-app-type: controller
spec:
  dnsPolicy: "ClusterFirst"
  runtimeClassName: kata-qemu-tdx
  nodeSelector:
    tdx-ac: "1"
  containers:
  - name: trusted-bigdl-llm-serving-tdx-controller # fixed
    image: intelanalytics/bigdl-ppml-trusted-bigdl-llm-serving-tdx:2.5.0-SNAPSHOT
    securityContext:
      privileged: true
      runAsUser: 0
    imagePullPolicy: Always
    env:
    - name: CONTROLLER_HOST # fixed
      value: "0.0.0.0"
    - name: CONTROLLER_PORT # fixed
      value: "21005"
    - name: API_HOST # fixed
      value: "0.0.0.0"
    - name: API_PORT # fixed
      value: "8000"
    - name: "ENABLE_ATTESTATION_API"
      value: "true"
    ports:
      - containerPort: 21005
        name: con-port
      - containerPort: 8000
        name: api-port
    resources:
      requests:
        memory: 16Gi
        cpu: 4
      limits:
        memory: 16Gi
        cpu: 4
    args: ["-m", "controller"]
    volumeMounts:
      - name: dev
        mountPath: /dev
  restartPolicy: "Never"
  volumes:
  - name: dev
    hostPath:
      path: /dev
---
# Service for the controller
apiVersion: v1
kind: Service
metadata:
  name: trusted-bigdl-llm-serving-tdx-a1234bd-controller-service
spec:
  # You may also want to change this to use the cluster's feature
  type: NodePort
  selector:
    fastchat-appid: a1234bd
    fastchat-app-type: controller
  ports:
    - name: cont-port
      protocol: TCP
      port: 21005
      targetPort: 21005
    - name: api-port
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trusted-bigdl-llm-serving-tdx-a1234bd-worker-deployment
spec:
  # Change this to the number you want
  replicas: 2
  selector:
    matchLabels:
      fastchat: worker
  template:
    metadata:
      labels:
        fastchat: worker
    spec:
      dnsPolicy: "ClusterFirst"
      runtimeClassName: kata-qemu-tdx
      nodeSelector:
        tdx-ac: "1"
      containers:
      - name: trusted-bigdl-llm-serving-tdx-worker # fixed
        image: intelanalytics/bigdl-ppml-trusted-bigdl-llm-serving-tdx:2.5.0-SNAPSHOT
        securityContext:
          runAsUser: 0
          privileged: true
        imagePullPolicy: Always
        env:
        - name: CONTROLLER_HOST # fixed
          value: trusted-bigdl-llm-serving-tdx-a1234bd-controller-service
        - name: CONTROLLER_PORT # fixed
          value: "21005"
        - name: WORKER_HOST # fixed
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: WORKER_PORT # fixed
          value: "21841"
        - name: MODEL_PATH # Change this
          value: "/ppml/models/vicuna-7b-bigdl/"
        - name: OMP_NUM_THREADS
          value: "16"
        - name: "ENABLE_ATTESTATION_API"
          value: "true"
        resources:
          requests:
            memory: 32Gi
            cpu: 16
          limits:
            memory: 32Gi
            cpu: 16
        args: ["-m", "worker"]
        volumeMounts:
          - name: dev
            mountPath: /dev
          - name: ppml-models
            mountPath: /ppml/models/
      restartPolicy: "Always"
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: ppml-models
        hostPath:
          path: /chatllm/models # change this in other envs
