name: 'Run Friesian Python Py37 Spark3'
description: 'Run Friesian Python Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.10'
        
    - name: Install dependencies
      shell: bash
      run: |
        apt-get update
        apt-get install wget
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools==58.0.4

    - name: Setup env
      shell: bash
      run: |
        conda create -n py37 -y python==3.7.10 setuptools==58.0.4
        conda info --env
        source activate py37
        pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib bigdl-dllib-spark3 bigdl-orca pyspark bigdl-orca-spark3 bigdl-chronos bigdl-chronos-spark3 bigdl-friesian bigdl-friesian-spark3
        pip uninstall -r .github/actions/python-requirements/requirements-dllib-python-ut-spark3.txt -y
        pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r .github/actions/python-requirements/requirements-dllib-python-ut-spark3.txt 
        pip install pytorch-lightning==1.4.8 
        pip install tensorboard==1.15.0 
        pip install google-api-core==1.26.1 google-auth==1.27.1 
        pip install google-auth-oauthlib==0.4.6 google-pasta==0.2.0 
        pip install googleapis-common-protos==1.51.0 matplotlib==3.2.1 
        pip install ray[default]==1.9.1 aiohttp==3.8.1 async-timeout==4.0.1 
        pip install wheel==0.34.2
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
