name: 'Run Friesian Python Py37 Spark3'
description: 'Run Friesian Python Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        cd scala
        ./make-dist.sh -P spark_3.x -Dspark.version=3.1.2
        cd -

        source activate py37
        #export SPARK_LOCAL_HOSTNAME=localhost
        pip install pyspark==3.1.2
        echo "tests 1"
        chmod a+x python/friesian/dev/test/run-pytests-friesian
        echo "tests 2"
        python/friesian/dev/test/run-pytests-friesian
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
