apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: $nfsPath
    server: $nfsServerIp
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigdl-ppml-notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigdl-ppml-notebook
  template:
    metadata:
      name: bigdl-ppml-notebook
      labels:
        app: bigdl-ppml-notebook
    spec:
      containers:
      - name: bigdl-ppml-notebook
        image: $imageName
        command: [ "/ppml/start-notebook-test.sh" ]
        ports:
        - containerPort: $jupyterPort
          hostPort: $jupyterPort
        env:
        - name: RUNTIME_K8S_SPARK_IMAGE
          value: $imageName
        - name: RUNTIME_SPARK_MASTER
          value: $k8sMasterURL
        - name: SGX_ENABLED
          value: "false"
        - name: JUPYTER_PORT
          value: "$jupyterPort"
        volumeMounts:
        - mountPath: /ppml/data
          name: nfs-storage
        - name: ssl-keys
          mountPath: /ppml/keys
        - name: ssl-password
          mountPath: /ppml/password
        - name: kubeconfig
          mountPath: /root/.kube
      nodeSelector:
        icx-1: "true"
      volumes:
      - name: ssl-keys
        secret:
          secretName: ssl-keys
      - name: ssl-password
        secret:
          secretName: ssl-password
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
      - name: kubeconfig
        secret:
          secretName: kubeconfig-secret
---
apiVersion: v1
kind: Service
metadata:
  name: bigdl-ppml-notebook
  labels:
    app: bigdl-ppml-notebook
spec:
  ports:
  - port: $jupyterPort
    targetPort: $jupyterPort
  type: NodePort
  selector:
    app: bigdl-ppml-notebook
