name: 'Mac Friesian ScalaTest Spark3.1'
description: 'Mac Friesian ScalaTest Spark3.1'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py36
        export SPARK_HOME=/opt/work/spark-3.1.2
        export KERAS_BACKEND=tensorflow
        
        cd scala
        mvn "-DwildcardSuites=com.intel.analytics.bigdl.friesian" test -P spark_3.x -Dspark.version=3.1.2
        cd -
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
        