name: 'Run Orca Basic Py37 Spark3'
description: 'Run Orca Basic Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py37
        export SPARK_LOCAL_HOSTNAME=localhost
        
        pip install -i https://pypi.python.org/simple --pre --upgrade bigdl-orca-spark3
        pip install orca[automl] orca[ray]
        pip list
        pip install pytest coverage
        cd python/orca
        coverage run -m pytest -v test/bigdl/orca
        coverage report -i
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
