name: 'Run Orca Python Exampletest Horovod Tf2 Py37 Spark3'
description: 'Run Orca Python Exampletest Horovod Tf2 Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py37
        export SPARK_LOCAL_HOSTNAME=localhost
        pip install -i https://pypi.python.org/simple --pre --upgrade bigdl-orca-spark3[ray]

        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} tensorflow==2.3.0
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} pillow
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} pyarrow
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} pandas
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} opencv-python-headless
        
        # build horovod
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} cmake
        HOROVOD_WITH_TENSORFLOW=1
        HOROVOD_WITH_GLOO=1
        pip install --no-cache-dir horovod==0.19.2

        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} grpcio==1.43.0
        chmod a+x python/orca/dev/example/run-example-test-ray-horovod-tf.sh
        python/orca/dev/example/run-example-test-ray-horovod-tf.sh
        ray stop
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
