apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvalut-es2-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: f95519c1-3fe8-441b-a7b9-368d5e13b534   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: keyvault-es2        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: enclave-key-pem
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions
        - |
          objectName: key-txt
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""
        - |
          objectName: keystore-jks
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""
        - |
          objectName: keystore-pkcs12
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""
        - |
          objectName: output-bin
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""
        - |
          objectName: server-crt
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""
        - |
          objectName: server-csr
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""
        - |
          objectName: server-key
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""
        - |
          objectName: server-pem
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""
    tenantId: 076293d2-5bf8-4aed-b73f-d8e82dacfc7e      # The tenant ID of the key vault
