name: 'Run Orca Python Horovod Pytorch Py37 Spark3'
description: 'Run Orca Python Horovod Pytorch Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py37
        export SPARK_LOCAL_HOSTNAME=localhost
        pip install -i https://pypi.org/simple --pre --upgrade bigdl-orca-spark3
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} -r grpcio==1.43.0
        chmod a+x python/orca/dev/test/run-pytests-horovod-pytorch.sh
        python/orca/dev/test/run-pytests-horovod-pytorch.sh
        ray stop
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
