name: 'Run Friesian Python Py37 Spark3'
description: 'Run Friesian Python Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        cd scala
        ./make-dist.sh -P spark_3.x -Dspark.version=3.1.2
        cd -
        mkdir data && cd data
        wget https://archive.apache.org/dist/spark/spark-3.1.2/spark-3.1.2-bin-hadoop2.7.tgz
        tar -xf spark-3.1.2-bin-hadoop2.7.tgz
        cd ..
        export SPARK_HOME=${{ github.workspace }}/data/spark-3.1.2-bin-hadoop2.7
        source activate py37
        export SPARK_LOCAL_HOSTNAME=localhost
        pip install pyspark==3.1.2 pytest
        chmod a+x python/friesian/dev/test/run-pytests-friesian
        python/friesian/dev/test/run-pytests-friesian
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
