name: 'Run Chronos Python3.9'
description: 'Run Chronos Python3.9'
runs:
  using: "composite"
  steps:
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Setup env
      shell: bash
      run: |
        conda remove -n chronos-py39-env -y --all
        conda create -n chronos-py39-env -y python==3.9 setuptools==58.0.4 -c ${GONDOLIN_CONDA_CHANNEL} --override-channels
        source activate chronos-py39-env
        apt-get update
        apt-get install -y libgl1
        apt-get install patchelf
        pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib bigdl-dllib-spark3 bigdl-orca pyspark bigdl-orca-spark3 bigdl-chronos bigdl-chronos-spark3 bigdl-nano bigdl-friesian bigdl-friesian-spark3
        source deactivate

      env:
        BIGDL_ROOT: ${{ github.workspace }}
