name: "Setup BigDL-LLM Env"
description: "BigDL-LLM installation"

runs:
  using: "composite"
  steps:
    - name: Create conda env for llm tests and conduct install tests
      shell: bash
      run: |
        pip install requests
        bash python/llm/dev/release_default_linux.sh default false
        whl_name=$(ls python/llm/dist)
        pip install -i https://pypi.python.org/simple "python/llm/dist/${whl_name}[all]"
        pip install pytest
        bash python/llm/test/run-llm-install-tests.sh
