name: 'Mac Dllib ScalaTest Spark2.4'
description: 'Mac Dllib ScalaTest Spark2.4'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py37
        export SPARK_HOME=$SPARK_2_4_HOME
        export KERAS_BACKEND=tensorflow
        cd scala
        mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.estimator" test -P spark_2.x -Dspark.version=2.4.6 && \
        mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.nnframes" test -P spark_2.x -Dspark.version=2.4.6 && \
        mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.keras" test -P spark_2.x -Dspark.version=2.4.6
        cd -
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}