name: 'Mac Friesian Python ExampleTest Feature Tf1 Spark3.1'
description: 'Mac Friesian Python ExampleTest Feature Tf1 Spark3.1'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source ~/.bash_profile
        source python/friesian/dev/prepare_env.sh
        source activate py37
        pip uninstall -y bigdl-dllib bigdl-orca bigdl-chronos bigdl-orca-spark3 bigdl-dllib-spark3 bigdl-chronos-spark3  pyspark
        export SPARK_HOME=/opt/work/spark-3.1.3
        cd scala
        ./make-dist.sh -P spark_3.x -Dspark.version=3.1.3
        cd -
        pip install pyspark==3.1.3
        pip install bigdl-tf bigdl-math
        echo "Running py37 tests"
        cd python/friesian/dev/test
        bash run-feature-example-tests.sh
        bash run-example-tests-tf1.15.0.sh

        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
        