AMX: false
batch_size: 128
cores: 80
cores_per_instance: 1
data_type: fp32
dnnl_verbose: false
exact_maxlen: 0
gpu_id: -1
graph_type: dynamic
history_maxlen: 100
history_minlen: 2
infer_hw: cpu
inference_instances: 80
inference_profiler: false
iterations: 1
mem: 480
mem_per_core: 6
mig: false
mig_inst_id: []
model_path: dien_fp32_dynamic_rnn_graph.pb
num_inter_threads: 1
num_intra_threads: 1
preproc_fw: spark
seed: 2