name: 'Run Chronos PRVN Python Spark3.1 Part1'
description: 'Run Chronos PRVN Python Spark3.1 Part1'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        sed -i "s/pyspark==2.4.6/pyspark==3.1.3/g" python/dllib/src/setup.py
        wget https://raw.githubusercontent.com/analytics-zoo/gha-cicd-env/main/python-requirements/requirements-chronos-python-ut.txt -O ${{ github.workspace }}/requirements-chronos-python-ut.txt
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} -r ${{ github.workspace }}/requirements-chronos-python-ut.txt
        bash python/dev/release_default_linux_spark3.sh default false false
        bash python/nano/dev/build_and_install.sh linux default false pytorch --force-reinstall --no-deps -U
        whl_name=`ls python/nano/dist/`
        pip install -i https://pypi.python.org/simple python/nano/dist/${whl_name}[tensorflow_27,pytorch,inference]
        pip install -i https://pypi.python.org/simple python/dllib/src/dist/bigdl_dllib_*-py3-none-manylinux1_x86_64.whl
        pip install -i https://pypi.python.org/simple python/orca/src/dist/bigdl_orca_*-py3-none-manylinux1_x86_64.whl
        pip install -i https://pypi.python.org/simple python/chronos/src/dist/bigdl_chronos_*-py3-none-manylinux1_x86_64.whl
        export SPARK_LOCAL_HOSTNAME=localhost
        export KERAS_BACKEND=tensorflow
        bash python/chronos/dev/test/run-pytests.sh 1
      env:
        BIGDL_ROOT: ${{ github.workspace }}
