name: 'BigDL-LLM example tests'
description: 'BigDL-LLM example tests'

runs:
  using: "composite"
  steps:
    - name: Test LLAMA2
      shell: bash
      env:
        INT4_CKPT_DIR: ./llm/ggml-actions/stable
        LLM_DIR: ./llm
        ORIGINAL_LLAMA2_PATH: ./llm/Llama-2-7b-chat-hf/
      
      run: |
        bash python/llm/dev/test/run-example-tests.sh
