name: "BigDL-LLM inference tests"
description: "BigDL-LLM inference tests"

runs:
  using: "composite"
  steps:
    - name: Test LLM inference
      shell: bash
      run: |
        python -m pip install einops datasets librosa
        bash python/llm/test/run-llm-inference-tests.sh
