apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeppelin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zeppelin-cluster-admin
subjects:
- kind: ServiceAccount
  name: zeppelin
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
