##### RecallInitializer Config

# default: 128, the dimensionality of the embedding vectors
# indexDim: 128

# default: null, path to saved index path, must be provided
indexPath: ./mnt/item_128.idx

itemIDColumn: tweet_id
itemEmbeddingColumn: prediction

# default: null, Only support parquet file
initialDataPath: ./mnt/item_ebd.parquet

# part: 27
