name: 'Remove BigDL-LLM Env'
description: 'Remove conda env for BigDL-LLM tests'

runs:
  using: "composite"
  steps:
    - name: Remove Conda Env
      shell: bash
      run: |
        $CONDA_HOME/bin/conda env remove -y -n bigdl-llm-test || true
