name: 'Mac Orca Python UT Ray Spark3.1'
description: 'Mac Orca Python UT Ray Spark3.1'
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

          #runs:
          #  using: "composite"
jobs:
  mac-ray-ut:
    runs-on: [self-hosted, mac, macOS]
    steps:
    - uses: actions/checkout@v3
      #    - name: Run Test
      #      uses: ./.github/actions/mac/orca/mac-orca-python-ut-ray-spark3
      #    - name: Create Job Badge
      #      uses: ./.github/actions/create-job-status-badge
      #      if: ${{ always() }}
      #      with:
      #        secret: ${{ secrets.GIST_SECRET}}
      #        gist-id: ${{env.GIST_ID}}
      #        is-self-hosted-runner: true
      #        file-name: Mac-Orca-Python-UT-Ray-Spark3.json
      #        type: job
      #        job-name: Mac-Orca-Python-UT-Ray-Spark3
      #        runner-hosted-on: 'Shanghai'
      #  steps:
    - name: Run Test
      shell: bash
      run: |
        source ~/.bash_profile
        source activate py37-tf2
        pip uninstall -y bigdl-dllib bigdl-orca bigdl-chronos bigdl-orca-spark3 bigdl-dllib-spark3 bigdl-chronos-spark3  pyspark
        export KERAS_BACKEND=tensorflow
        export SPARK_HOME=/opt/work/spark-3.1.3
        export MASTER=local[4]
        export HDFS_URI=/Users/arda/data
        
        gsed -i "s/'pyspark=='+PYSPARK_VERSION/'pyspark==3.1.2'/g" python/dllib/src/setup.py
        gsed -i "s/name='bigdl-dllib'/name='bigdl-dllib-spark3'/g" python/dllib/src/setup.py
        gsed -i "s/dist\/bigdl_dllib-/dist\/bigdl_dllib_spark3-/g" python/dllib/dev/release/release.sh
        bash python/dllib/dev/release/release.sh mac default false false -Dspark.version=3.1.3 -P spark_3.x ${profiles}

        gsed -i "s/bigdl-dllib==/bigdl-dllib-spark3==/g" python/orca/src/setup.py
        gsed -i "s/name='bigdl-orca'/name='bigdl-orca-spark3'/g" python/orca/src/setup.py
        gsed -i "s/dist\/bigdl_orca-/dist\/bigdl_orca_spark3-/g" python/orca/dev/release/release.sh
        bash python/orca/dev/release/release.sh mac default true false -Dspark.version=3.1.3 -P spark_3.x

        echo "Running py37 tests"
        # install dllib
        pip install -i https://pypi.org/simple python/dllib/src/dist/bigdl_dllib*-py3-none-macosx_10_11_x86_64.whl	
        # install orca
        pip install -i https://pypi.org/simple python/orca/src/dist/bigdl_orca*-py3-none-macosx_10_11_x86_64.whl		
        
        chmod a+x python/orca/dev/test/run-pytests-ray.sh
        python/orca/dev/test/run-pytests-ray.sh
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
        
