name: 'Run Orca Jep UT Py37 Spark3'
description: 'Run Orca Jep UT Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py37
        export SPARK_LOCAL_HOSTNAME=localhost
        chmod a+x python/orca/dev/test/run-pytests-jep.sh
        bash python/orca/dev/test/run-pytests-jep.sh
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
