apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "friesian-serving.recall.fullname" . }}
  namespace: {{ template "friesian-serving.namespace" . }}
  labels:
    app: {{ template "friesian-serving.name" . }}-recall
    {{ include "friesian-serving.labels" . | nindent 4 }}
    {{- if .Values.recall.labels }}
    {{ toYaml .Values.recall.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.recall.annotations }}
  annotations:
    {{ toYaml .Values.recall.annotations | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    indexPath: /resources/{{ .Values.recall.resourcePath.indexPath }}
    {{- with .Values.recall.config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    featureServiceURL: {{ include "friesian-serving.feature-recall.fullname" . }}:{{ .Values.featureRecall.config.servicePort }}