apiVersion: v1
kind: Service
metadata:
  name: {{ include "friesian-serving.recall.fullname" . }}
  namespace: {{ template "friesian-serving.namespace" . }}
  labels:
    app: {{ template "friesian-serving.name" . }}-recall
    {{ include "friesian-serving.labels" . | nindent 4 }}
    {{- if .Values.recall.labels }}
    {{ toYaml .Values.recall.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.recall.annotations }}
  annotations:
    {{ toYaml .Values.recall.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.recall.service.type }}
  clusterIP: {{ .Values.recall.service.clusterIP }}
  selector:
    app: {{ template "friesian-serving.name" . }}-recall
  ports:
    - name: service
      protocol: TCP
      port: {{ .Values.recall.config.servicePort }}
      targetPort: {{ .Values.recall.config.servicePort }}
    - name: monitor
      port: {{ .Values.recall.config.monitorPort }}
      targetPort: {{ .Values.recall.config.monitorPort }}
      protocol: TCP
