apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigdl-ppml-notebook
  namespace: bigdl-ppml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigdl-ppml-notebook
  template:
    metadata:
      name: bigdl-ppml-notebook
      labels:
        app: bigdl-ppml-notebook
    spec:
      serviceAccountName: bigdl-ppml-sa
      containers:
      - name: bigdl-ppml-notebook
        image: {{ .Values.imageName }}
        command: [ "/ppml/start-notebook.sh" ]
        ports:
        - containerPort: {{ .Values.jupyterPort }}
          hostPort: {{ .Values.jupyterPort }}
        env:
        - name: RUNTIME_K8S_SPARK_IMAGE
          value: {{ .Values.imageName }}
        - name: RUNTIME_SPARK_MASTER
          value: {{ .Values.k8sMasterURL }}
        - name: RUNTIME_DRIVER_MEMORY
          value: {{ .Values.driverMemory}}
        - name: SGX_ENABLED
        {{- if eq .Values.TEEMode "tdx" }}
          value: "false"
        {{- else }}
          value: "true"
        {{- end }}
        - name: JUPYTER_PORT
          value: "{{ .Values.jupyterPort }}"
        volumeMounts:
        - name: nfs-storage
          mountPath: /ppml/data
        - name: nfs-storage
          mountPath: /root/.jupyter
          subPath: .jupyter
        - name: ssl-keys
          mountPath: /ppml/keys
        - name: ssl-password
          mountPath: /ppml/password
        - name: kubeconfig
          mountPath: /root/.kube
      {{- if eq .Values.TEEMode "sgx" }}
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: aesm-socket
          mountPath: /var/run/aesmd/aesm.socket
      resources:
          requests:
            cpu: 8
            memory: 32Gi
            sgx.intel.com/epc: 34359738368
            sgx.intel.com/enclave: 1
            sgx.intel.com/provision: 1
          limits:
            cpu: 10
            memory: 40Gi
            sgx.intel.com/epc: 34359738368
            sgx.intel.com/enclave: 1
            sgx.intel.com/provision: 1
      {{- end }}
      volumes:
      - name: ssl-keys
        secret:
          secretName: ssl-keys
      - name: ssl-password
        secret:
          secretName: ssl-password
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-pvc
      - name: kubeconfig
        secret:
          secretName: kubeconfig-secret
      {{- if eq .Values.TEEMode "sgx" }}
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: aesm-socket
        hostPath:
          path: /var/run/aesmd/aesm.socket
      {{- end }}
