name: 'Run Orca Basic Tf2 Py39 Spark3'
description: 'Run Orca Basic Tf2 Py39 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py39
        export SPARK_LOCAL_HOSTNAME=localhost
        
        pip install -i https://pypi.python.org/simple --pre --upgrade bigdl-orca-spark3
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} tensorflow==2.9.0
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} grpcio==1.43.0
        pip list
        chmod a+x python/orca/dev/test/run-pytests-basic-tf2.sh
        python/orca/dev/test/run-pytests-basic-tf2.sh
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}