name: 'Setup Nano PyTorch Env'
description: 'setup nano pytorch env'

inputs:
  python-version: 
    description: 'python version'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        apt-get update && apt-get install -y wget libgl1

        conda remove -n nano-pytorch -y --all
        conda create -n nano-pytorch -y python==${PYTHON_VERSION} setuptools==58.0.4
        source activate nano-pytorch

        pip install -y pytest
        pip install -y --pre --upgrade bigdl-nano[pytorch,inference]

        # required by Ray test
        pip install -y google-api-core==2.8.2
        pip install -y ray[default]==1.11.0 prometheus_client==0.13.0

        # required by Automl test
        pip install -y ConfigSpace optuna

        # required by NoteBook and Tutorial test
        pip install -y nbmake==1.3.0 lightning-bolts==0.5.0 ipykernel==5.5.6 matplotlib

        source deactivate
    - env:
      PYTHON_VERSION: ${{ inpus.python-version }}