name: 'Setup Nano PyTorch Env'
description: 'setup nano pytorch env'

inputs:
  python-version:
    description: 'python version'
    required: true
  os:
    description: 'ubuntu or centos or windows'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install System Dependencies
      shell: bash
      run: |
        if [ $OS = "ubuntu" ]; then
          sudo apt-get update && sudo apt-get install -y wget libgl1
        elif [ $OS = "centos" ]; then
          export http_proxy=$HTTP_PROXY
          export https_proxy=$HTTPS_PROXY
          yum install -y gcc mesa-libGL
        else
          :
        fi
      env:
        OS: ${{ inputs.os }}

    - name: Setup Python (Ubuntu and Windows)
      if: ${{ inputs.os != 'centos' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup Python (CentOS)
      if: ${{ inputs.os == 'centos' }}
      shell: bash
      run: |
        $CONDA_HOME/bin/conda remove -n nano-pytorch -y --all
        $CONDA_HOME/bin/conda create -n nano-pytorch -y python==${PYTHON_VERSION}
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}

    - name: Install Nano[pytorch,inference]
      shell: bash
      run: |
        if [ $OS = "centos" ]; then
          source $CONDA_HOME/bin/activate nano-pytorch
        fi
        if [ $IS_PR = "false" ]; then
          pip install --pre --upgrade bigdl-nano[pytorch,inference]
          if [ ! $OS = "windows" ]; then
            pip install oneccl_bind_pt==1.13 -f https://developer.intel.com/ipex-whl-stable-cpu
          fi
        else
          pip install wheel
          if [ ! $OS = "windows" ]; then
            bash python/nano/dev/build_and_install.sh linux default false pytorch,inference
            pip install oneccl_bind_pt==1.13 -f https://developer.intel.com/ipex-whl-stable-cpu
          else
            bash python/nano/dev/build_and_install.sh windows default false pytorch,inference
          fi
        fi
      env:
        OS: ${{ inputs.os }}
        IS_PR: ${{ github.event.pull_request != null }}

    - name: Install Python Dependencies
      shell: bash
      run: |
        if [ $OS = "centos" ]; then
          source $CONDA_HOME/bin/activate nano-pytorch
        fi
        pip install pytest

        # required by Ray test
        pip install google-api-core==2.8.2
        pip install ray[default]==1.11.0 prometheus_client==0.13.0

        # required by Automl test
        pip install ConfigSpace optuna

        # required by NoteBook and Tutorial test
        pip install nbmake==1.3.0 lightning-bolts==0.5.0 ipykernel==5.5.6 matplotlib

        # required by OpenVINO and IPEX test
        pip install diffusers==0.11.1
      env:
        OS: ${{ inputs.os }}
