name: 'Setup Nano PyTorch Env'
description: 'setup nano pytorch env'

inputs:
  python-version: 
    description: 'python version'
    required: true
  os:
    description: 'ubuntu or windows'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install System Dependencies (Ubuntu)
      if: inputs.os=='ubuntu'
      shell: bash
      run: |
        apt-get update && apt-get install -y wget libgl1

    - name: Install System Dependencies (CentOS)
      if: inputs.os == 'centos'
      shell: bash
      run: |
        export http_proxy=$HTTP_PROXY
        export https_proxy=$HTTPS_PROXY
        yum install -y gcc mesa-libGL

    - name: Install System Dependencies (Windows)
      if: inputs.os=='windows'
      shell: bash
      run: |
        echo "123"

    - name: Install Nightly Nano
      if: github.event.pull_request == null
      shell: bash
      run: pip install --pre --upgrade bigdl-nano[pytorch,inference]

    - name: Install Main Branch Nano
      if: github.event.pull_request != null
      shell: bash
      run: bash python/nano/dev/build_and_install.sh linux default false pytorch,inference

    - name: Install Python Dependencies
      shell: bash
      run: |
        pip install pytest

        # required by Ray test
        pip install google-api-core==2.8.2
        pip install ray[default]==1.11.0 prometheus_client==0.13.0

        # required by Automl test
        pip install ConfigSpace optuna

        # required by NoteBook and Tutorial test
        pip install nbmake==1.3.0 lightning-bolts==0.5.0 ipykernel==5.5.6 matplotlib

        # required by OpenVINO and IPEX test
        pip install diffusers==0.11.1
