apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigdl-torchserve-backend-deployment
spec:
  selector:
    matchLabels:
      app: torchserve-backend
  replicas: {{ .Values.backendNum }}
  template:
    metadata:
      labels:
        app: torchserve-backend
    spec:
      containers:
      - name: bigdl-torchserve-backend-pod
        image: {{ .Values.imageName }}
        command: ['sh' , '-c', 'bash /ppml/torchserve/backend-entrypoint.sh']
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /ppml/work/data
          name: nfs-storage
        {{- if eq .Values.TEEMode "sgx" }}
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: aesm-socket
          mountPath: /var/run/aesmd/aesm.socket
        {{- end }}
        env:
        - name: PCCS_URL
          value: "{{ .Values.PCCSUrl }}"
        - name: FRONTEND_IP
          value: {{ .Values.frontendIP }}
        - name: FRONTEND_MANAGEMENT_PORT
          value: {{ .Values.managementPort }}
        - name: MODEL_NAME
          value: "{{ .Values.modelName }}"
        - name: SGX_ENABLED
        {{- if eq .Values.TEEMode "sgx" }}
          value: "true"
        {{- else }}
          value: "false"
        {{- end }} 
        - name: ATTESTATION
          value: "{{ .Values.attestation }}"
        - name: BACKEND_PORT
          value: "{{ .Values.backendPort }}"
        {{- if eq .Values.TEEMode "sgx" }}
        resources:
          requests:
            cpu: 1
            memory: 10Gi
            sgx.intel.com/epc: 21474836280
            sgx.intel.com/enclave: 1
            sgx.intel.com/provision: 1
          limits:
            cpu: 1
            memory: 10Gi
            sgx.intel.com/epc: 21474836280
            sgx.intel.com/enclave: 1
            sgx.intel.com/provision: 1
        {{- end }} 
        volumes:
        - name: nfs-storage
          persistentVolumeClaim:
          claimName: nfsvolumeclaim
        {{- if eq .Values.TEEMode "sgx" }}
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: aesm-socket
          hostPath:
            path: /var/run/aesmd/aesm.socket
        {{- end }}

