name: 'Run Orca Ray Ctx'
description: 'Run Orca Ray Ctx'
runs:
  using: "composite"
  steps:
    - name: Setup Env
      run: |
        apt-get update
        apt-get install wget
    
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools==58.0.4

        pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib bigdl-dllib-spark3 bigdl-orca pyspark bigdl-orca-spark3 bigdl-chronos bigdl-chronos-spark3 bigdl-friesian bigdl-friesian-spark3
        pip uninstall -r python/orca/dev/example/requirements-ray.txt -y
        pip install -i https://pypi.org/simple --pre --upgrade bigdl-orca-spark3
        pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r python/orca/dev/example/requirements-ray.txt

        pip install pytest
        pip install tensorflow==2.8.0
        pip install ray==1.11.0
        pip install --pre --upgrade bigdl-orca
        
    - name: Run Test
      run: |
        export SPARK_LOCAL_HOSTNAME=localhost
        chmod a+x python/orca/dev/test/run-pytests-ray-ctx.sh
        python/orca/dev/test/run-pytests-ray-ctx.sh
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
