######## Feature Service

### Basic setting

# Default: 8980, which port to create the server
servicePort: 8085

# Default: null, open a port for prometheus monitoring tool, if set, user can check the
# performance using prometheus
monitorPort: 1236

# default: "", prefix for redis key
redisKeyPrefix: 2tower_item_

# default: 0, item slot type on redis cluster. 0 means slot number use the default value 16384, 1 means all keys save to same slot, 2 means use the last character of id as hash tag.
redisClusterItemSlotType:

# default: 2, The redis log emit interval in minutes
logInterval: 2
