##### RecallInitializer Config

# default: 128, the dimensionality of the embedding vectors
indexDim: 50

# default: null, path to saved index path, must be provided
indexPath: ./item_50.idx

itemIDColumn: tweet_id
itemEmbeddingColumn: prediction

# default: null, Only support parquet file
initialDataPath: /Users/guoqiong/intelWork/data/friesian_service/from_yina/item_ebd.parquet.parquet

part: 27
