name: 'Run Orca Python Exampletest Horovod Tf2 Py37 Spark3'
description: 'Run Orca Python Exampletest Horovod Tf2 Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py37
        export SPARK_LOCAL_HOSTNAME=localhost
        bash python/dev/release_default_linux_spark313.sh default false false
        
        # install dllib
        pip install python/dllib/src/dist/bigdl_dllib*-py3-none-manylinux1_x86_64.whl

        # install orca
        pip install python/orca/src/dist/bigdl_orca*-py3-none-manylinux1_x86_64.whl

        chmod a+x python/orca/dev/example/run-example-test-ray-horovod-tf.sh
        python/orca/dev/example/run-example-test-ray-horovod-tf.sh
        ray stop
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
