apiVersion: batch/v1
kind: Job
metadata:
  name: spark-pi-job
spec:
  template:
    spec:
      restartPolicy: Never
      hostNetwork: true
      containers:
      - name: spark-local-k8s-client
        image:  {{ .Values.image }}
        imagePullPolicy: Never
        command: ["/bin/sh","-c"]
        args: ["sed -i \"s@/home/sdp/glorysdj/enclave-key.pem@$OUTSIDE_ENCLAVE_KEY_PATH@g\" spark-executor-template.yaml;
                sed -i \"s@/home/sdp/glorysdj/kubernetes/kubeconfig@$OUTSIDE_KUBECONFIG_PATH@g\" spark-executor-template.yaml;
                sed -i \"s@/home/sdp/glorysdj/data@$OUTSIDE_DATA_PATH@g\" spark-executor-template.yaml;
                cp mounts/kubeconfig /root/.kube/config;
                cp mounts/enclave-key.pem /graphene/Pal/src/host/Linux-SGX/signer;
                export RUNTIME_DRIVER_HOST=$( hostname -I | awk '{print $1}' );
                export LOCAL_IP=$( hostname -I | awk '{print $1}' );
                bash ./init.sh;
                bash /ppml/trusted-big-data-ml/mounts/submit-spark-k8s.sh | tee output.log
                "]
        securityContext:
          privileged: true
        env:
          - name: OUTSIDE_ENCLAVE_KEY_PATH
            value: {{ .Values.enclaveKeysPath }}
          - name: OUTSIDE_KUBECONFIG_PATH
            value: {{ .Values.kubeconfigPath }}
          - name: OUTSIDE_DATA_PATH
            value: {{ .Values.dataPath }}
          - name: RUNTIME_SPARK_MASTER
            value: {{ .Values.k8sMaster}}
          - name: RUNTIME_K8S_SERVICE_ACCOUNT
            value: "spark"
          - name: RUNTIME_K8S_SPARK_IMAGE
            value: {{ .Values.image }}
          - name: RUNTIME_DRIVER_PORT
            value: "54321"
          - name: RUNTIME_EXECUTOR_INSTANCES
            value: "1"
          - name: RUNTIME_EXECUTOR_CORES
            value: "4"
          - name: RUNTIME_EXECUTOR_MEMORY
            value: "20g"
          - name: RUNTIME_TOTAL_EXECUTOR_CORES
            value: "4"
          - name: RUNTIME_DRIVER_CORES
            value: "4"
          - name: RUNTIME_DRIVER_MEMORY
            value: "10g"
          - name: SGX_MEM_SIZE
            value: "32G"
          - name: SGX_LOG_LEVEL
            value: "error"
        resources:
          requests:
            cpu: 1
          limits:
            cpu: 4
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
          - name: dev-gsgx
            mountPath: /dev/gsgx
          - name: aesm-socket
            mountPath: /var/run/aesmd/aesm.socket
          - name: secure-keys
            mountPath: /ppml/trusted-big-data-ml/work/keys
          - name: secure-password
            mountPath: /ppml/trusted-big-data-ml/work/password
          - name: nfs-storage
            mountPath: "/ppml/trusted-big-data-ml/mounts"
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev-gsgx
        hostPath:
          path: /dev/gsgx
      - name: aesm-socket
        hostPath:
          path: /var/run/aesmd/aesm.socket
      - name: secure-keys
        secret:
          secretName: ssl-keys
      - name: secure-password
        secret:
          secretName: ssl-password
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: {{ .Values.pvc }}
