apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bigdl-ppml-storage-role-binding
  namespace: bigdl-ppml-jupyter
subjects:
  - kind: ServiceAccount
    name: bigdl-ppml-sa
    namespace: bigdl-ppml-jupyter
roleRef:
  kind: ClusterRole
  name: bigdl-ppml-cluster-role
  apiGroup: rbac.authorization.k8s.io
