apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bigdl-ppml-service-role
  namespace: bigdl-ppml-jupyter
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "create", "patch", "get", "update", "list"]
