apiVersion: v1
kind: Service
metadata:
  name: bigdl-ppml-notebook
  namespace: bigdl-ppml-jupyter
  labels:
    app: bigdl-ppml-notebook
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.jupyterPort }}
    targetPort: {{ .Values.jupyterPort }}
  selector:
    app: bigdl-ppml-notebook
  sessionAffinity: ClientIP
  externalIPs:
  - {{ .Values.notebookExternalIP }}
