apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-pv
  labels:
    app: models
spec:
  capacity:
    storage: 10Gi #Modify according to model size
  accessModes:
    - ReadWriteMany
  storageClassName: models
  nfs:
    path: YOUR_NFS_PATH
    server: YOUR_NFS_SERVER
