name: 'Run Orca Jep UT Py37 Spark3'
description: 'Run Orca Jep UT Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py37
        export SPARK_LOCAL_HOSTNAME=localhost

        pip install -i https://pypi.org/simple --pre --upgrade bigdl-orca-spark3

        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} torch==1.7.1
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} torchvision==0.8.2
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} jep==3.9.0
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} cloudpickle
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} pandas
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} deprecated

        chmod a+x python/orca/dev/test/run-pytests-jep.sh
        bash python/orca/dev/test/run-pytests-jep.sh
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
