name: 'Run Orca Python Ray Py37 Spark3'
description: 'Run Orca Python Ray Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py37
        export SPARK_LOCAL_HOSTNAME=localhost
        pip install -i https://pypi.org/simple --pre --upgrade bigdl-orca-spark3
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} ray[default]==1.9.2
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} protobuf==3.15.3
        
        chmod a+x python/orca/dev/test/run-pytests-ray
        python/orca/dev/test/run-pytests-ray
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
