name: 'Run Orca Python Ray Py37 Spark3'
description: 'Run Orca Python Ray Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py37
        export SPARK_LOCAL_HOSTNAME=localhost
        pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib-spark3 bigdl-orca-spark3 bigdl-chronos-spark3 pyspark bigdl-orca bigdl-dllib bigdl-chronos bigdl-tf bigdl-math
        pip install -i https://pypi.org/simple --pre --upgrade bigdl-orca-spark3
        chmod a+x python/orca/dev/test/run-pytests-ray
        python/orca/dev/test/run-pytests-ray
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
