name: 'Run Orca Python Py37 Spark3'
description: 'Run Orca Python Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Setup Env
      shell: bash
      run: |
        apt-get update
        apt-get install wget

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools==58.0.4
        
    - name: Run Test
      shell: bash
      run: |
        conda remove -n orca-python-horovod-pytorch-py37 -y --all
        conda create -n orca-python-horovod-pytorch-py37 -y python==3.7.11 setuptools==58.0.4
        conda info -e
        source activate orca-python-horovod-pytorch-py37
        pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib bigdl-dllib-spark3 bigdl-orca pyspark bigdl-orca-spark3 bigdl-chronos bigdl-chronos-spark3 bigdl-friesian bigdl-friesian-spark3
        conda install -y pytorch==1.4.0 torchvision==0.5.0 cpuonly -c pytorch
        pip install cmake==3.16.0

        HOROVOD_WITH_PYTORCH=1; HOROVOD_WITH_GLOO=1; pip install --no-cache-dir horovod==0.19.2
        pip uninstall -r .github/actions/python-requirements/requirements-horovod-pytorch.txt -y
        pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r .github/actions/python-requirements/requirements-horovod-pytorch.txt 
        pip install -i https://pypi.org/simple --pre --upgrade bigdl-orca-spark3
        pip uninstall -y opencv-python-headless
        pip install opencv-python-headless

        export SPARK_LOCAL_HOSTNAME=localhost
        chmod a+x python/orca/dev/test/run-pytests-horovod-pytorch.sh
        python/orca/dev/test/run-pytests-horovod-pytorch.sh
        ray stop

        source deactivate
        conda remove -n orca-python-horovod-pytorch-py37 --all
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
