apiVersion: v1
kind: Pod
metadata:
  name: spark-deployment
  namespace: default
spec:
  containers:
  - name: spark-example
    imagePullPolicy: Never
    volumeMounts:
    - name: device-plugin
      mountPath: /var/lib/kubelet/device-plugins
#    - name: sgx-enclave
#      mountPath: /dev/sgx/enclave
#    - name: sgx-provision
#      mountPath: /dev/sgx/provision
    - name: aesm
      mountPath: /var/run/aesmd
    - name: data-exchange
      mountPath: /opt/occlum_spark/data
#    securityContext:
#      privileged: true  using device-plugin to mount sgx env don't need the privileged
    resources:
      requests:
        cpu: 4
        memory: 2Gi
        sgx.intel.com/epc: 16106127360
        sgx.intel.com/enclave: 1
        sgx.intel.com/provision: 1
      limits:
        cpu: 10
        memory: 5Gi
        sgx.intel.com/epc: 16106127360
        sgx.intel.com/enclave: 1
        sgx.intel.com/provision: 1
    env:
    - name: NETTY_THREAD
      value: "32"
    - name: SGX_MEM_SIZE
      value: "15GB"
    - name: SGX_THREAD
      value: "1024"
    - name: SGX_HEAP
      value: "512MB"
    - name: SGX_KERNEL_HEAP
      value: "1GB"
    - name: ATTESTATION
      value: false
    - name: PCCS_URL
      value: "https://PCCS_IP:PCCS_PORT"
    - name: ATTESTATION_URL
      value: "ESHM_IP:EHSM_PORT"
    - name: APP_ID
      value: your_app_id
    - name: API_KEY
      value: your_api_key
    - name: CHALLENGE
      value: cHBtbAo=
    - name: REPORT_DATA
      value: ppml
  volumes:
    - name: device-plugin
      hostPath:
        path: /var/lib/kubelet/device-plugins
#  - name: sgx-enclave
#    hostPath:
#      path: /dev/sgx_enclave
#  - name: sgx-provision
#    hostPath:
#      path: /dev/sgx_provision
    - name: aesm
      hostPath:
        path: /var/run/aesmd
    - name: data-exchange
      hostPath:
        path: /tmp
