# pccs Service
apiVersion: v1
kind: Service
metadata:
  name: pccs
  namespace: bigdl-pccs
  labels:
    app: pccs
spec:
  type: ClusterIP
  ports:
    - name: pccs
      port: 18081
      targetPort: 18081
  selector:
    app: pccs
  externalIPs:
  - {{ .Values.pccsIP }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pccs
  namespace: bigdl-pccs
spec:
  selector:
    matchLabels:
      app: pccs
  serviceName: "pccs"
  replicas: 1
  template:
    metadata:
      labels:
        app: pccs
    spec:
      containers:
      - name: pccs
        image: {{ .Values.pccsImageName }}
        imagePullPolicy: IfNotPresent
        env:
        - name: API_KEY
          value: {{ .Values.apiKey }}
        - name: PCCS_PORT
          value: "18081"
        - name: HTTPS_PROXY_URL
          value: {{ .Values.httpsProxyUrl }}
        - name: COUNTRY_NAME
          value: {{ .Values.countryName }}
        - name: CITY_NAME
          value: {{ .Values.cityName }}
        - name: ORGANIZATION_NAME
          value: {{ .Values.organizaitonName }}
        - name: COMMON_NAME
          value: {{ .Values.commonName }}
        - name: EMAIL_ADDRESS
          value: {{ .Values.emailAddress }}
        - name: PASSWORD
          value: {{ .Values.serverPassword }}
        ports:
        - containerPort: 18081
          name: pccs-port
---