name: 'Mac Dllib Python ExampleTest Spark3.1'
description: 'Mac Dllib Pythom ExampleTest Spark3.1'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        source activate py37
        export KERAS_BACKEND=tensorflow
        chmod a+x python/dllib/examples/run-example-tests-pip.sh 
        gsed -i "s/pyspark==2.4.6/pyspark==3.1.3/g" python/dllib/src/setup.py
        gsed -i "s/name='bigdl-dllib'/name='bigdl-dllib-spark3'/g" python/dllib/src/setup.py
        gsed -i "s/dist\/bigdl_dllib-/dist\/bigdl_dllib_spark3-/g" python/dllib/dev/release/release.sh
        bash python/dllib/dev/release/release.sh mac default false false -Dspark.version=3.1.3 -P spark_3.x ${profiles}
        pip install python/dllib/src/dist/bigdl_dllib*-py3-none-macosx_10_11_x86_64.whl
        python/dllib/examples/run-example-tests-pip.sh
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
        