name: 'Setup Nano TensorFlow Env'
description: 'setup nano tensorflow env'

inputs:
  python-version:
    description: 'python version'
    required: true
  os:
    description: 'ubuntu or centos or windows'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install System Dependencies
      shell: bash
      run: |
        if [ $OS = "ubuntu" ]; then
          sudo apt-get update && sudo apt-get install -y wget libgl1
        elif [ $OS = "centos" ]; then
          export http_proxy=$HTTP_PROXY
          export https_proxy=$HTTPS_PROXY
          yum install -y gcc mesa-libGL
        else
          :
        fi
      env:
        OS: ${{ inputs.os }}

    - name: Setup Python (Ubuntu and Windows)
      if: ${{ inputs.os != 'centos' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup Python (CentOS)
      if: ${{ inputs.os == 'centos' }}
      shell: bash
      run: |
        $CONDA_HOME/bin/conda remove -n nano-tensorflow -y --all
        $CONDA_HOME/bin/conda create -n nano-tensorflow -y python==${PYTHON_VERSION}
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}

    - name: Install Nano[tensorflow,inference]
      shell: bash
      run: |
        if [ $OS = "centos" ]; then
          source $CONDA_HOME/bin/activate nano-tensorflow
        fi
        if [ $IS_PR = "false" ]; then
          pip install --pre --upgrade bigdl-nano[tensorflow,inference]
        else
          pip install wheel
          bash python/nano/dev/build_and_install.sh linux default false tensorflow,inference
        fi
        if [ $OS = "centos" ]; then
          source bigdl-nano-init
          echo "export http_proxy=$HTTP_PROXY" >> $CONDA_PREFIX/bin/bigdl-nano-init
          echo "https_proxy=$HTTPS_PROXY" >> $CONDA_PREFIX/bin/bigdl-nano-init
        fi
      env:
        OS: ${{ inputs.os }}
        IS_PR: ${{ github.event.pull_request != null }}

    - name: Install Python Dependencies
      shell: bash
      run: |
        if [ $OS = "centos" ]; then
          source $CONDA_HOME/bin/activate nano-tensorflow
        fi
        # fail to install horovod
        # # required by Horovod test
        # HOROVOD_WITH_MPI=1 HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 pip install --no-cache-dir horovod==0.25.0

        # required by Ray test
        pip install google-api-core==2.8.2
        pip install ray[default]==1.11.0 prometheus_client==0.13.0

        # required by Automl test
        pip install ConfigSpace optuna

        # required by NoteBook and Tutorial test
        pip install tensorflow-datasets jinja2 jupyter nbconvert nbmake
      env:
        OS: ${{ inputs.os }}
