name: 'Setup Nano TensorFlow Env'
description: 'setup nano tensorflow env'

inputs:
  python-version: 
    description: 'python version'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        apt-get update && apt-get install -y wget libgl1

        conda remove -n nano-tensorflow -y --all
        conda create -n nano-tensorflow -y python==${PYTHON_VERSION} setuptools==58.0.4
        source activate nano-tensorflow

        pip install -y pytest
        pip install -y --pre --upgrade bigdl-nano[tensorflow,inference]

        # required by Horovod test
        HOROVOD_WITH_MPI=1 HOROVOD_WITH_TENSORFLOW=1 HOROVOD_WITHOUT_PYTORCH=1 pip install --no-cache-dir horovod==0.25.0

        # required by Ray test
        pip install -y google-api-core==2.8.2
        pip install -y ray[default]==1.11.0 prometheus_client==0.13.0

        # required by Automl test
        pip install -y ConfigSpace optuna

        # required by NoteBook and Tutorial test
        pip install -y tensorflow-datasets nbmake==1.3.0 lightning-bolts==0.5.0 ipykernel==5.5.6 matplotlib

        source deactivate
    - env:
      PYTHON_VERSION: ${{ inpus.python-version }}