name: 'Run Orca Notebook Xshards'
description: 'Run Orca Notebook Xshards'
runs:
  using: "composite"
  steps:
    - name: Setup Env
      shell: bash
      run: |
        apt-get update
        apt-get install wget

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools==58.0.4
        
    - name: Run Test
      shell: bash
      run: |
        conda remove -n orca-notebook-py37 -y --all
        conda create -n orca-notebook-py37 -y python==3.7.10 setuptools==58.0.4 -c ${GONDOLIN_CONDA_CHANNEL} --override-channels
        conda info -e
        
        wget https://archive.apache.org/dist/spark/spark-3.1.3/spark-3.1.3-bin-hadoop2.7.tgz -O ${{ github.workspace }}/spark-3.1.3-bin-hadoop2.7.tgz
        tar -xf spark-3.1.3-bin-hadoop2.7.tgz -C ${{ github.workspace }}/
        export SPARK_HOME=${{ github.workspace }}/spark-3.1.3-bin-hadoop2.7

        source activate orca-notebook-py37
        pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib bigdl-dllib-spark3 bigdl-orca pyspark bigdl-orca-spark3 bigdl-chronos bigdl-chronos-spark3 bigdl-friesian bigdl-friesian-spark3
        wget https://raw.githubusercontent.com/analytics-zoo/gha-cicd-env/main/python-requirements/requirements-orca-python-ray.txt -O ${{ github.workspace }}/requirements-orca-python-ray.txt
        pip uninstall -r ${{ github.workspace }}/requirements-orca-python-ray.txt -y
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} -r ${{ github.workspace }}/requirements-orca-python-ray.txt
        export SPARK_LOCAL_HOSTNAME=localhost
        export FTP_URI=${FTP_URI}

        
        source deactivate
        conda remove -n orca-notebook-py37 -y --all
      env:
        BIGDL_ROOT: ${{ github.workspace }}