name: 'Orca Docker Test'
description: 'Orca Docker Test'
inputs:
  image:
    description: 'image'
    required: true
    default: '10.239.45.10/arda/intelanalytics/bigdl-orca'
  image-tag:
    description: 'image tag'
    required: true
    default: 'latest'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set Variable
      shell: bash
      env:
        DEFAULT_IMAGE: ${{ inputs.image }}:${{ inputs.image-tag }}
      run: |
        whoami
        export IMAGE=${{ env.DEFAULT_IMAGE }}
        export http_proxy="$HTTP_PROXY"
        export https_proxy="$HTTPS_PROXY"
        export no_proxy="$NO_PROXY"

    - name: Start Container
      shell: bash
      run: |
        set -x
        export CONTAINER_NAME=orca-docker-test
        docker container rm ${CONTAINER_NAME} -f

        docker run -itd \
            --net=host \
            --env http_proxy="http://child-prc.intel.com:913" \
            --env https_proxy="http://child-prc.intel.com:913" \
            --name=${CONTAINER_NAME} \
            $IMAGE \
            bash -c "pip install tensorflow==2.9.0 torch==1.7.1 pytest argparse && export GIT_SSL_NO_VERIFY=1 && git clone https://github.com/intel-analytics/BigDL.git && cd BigDL/python/orca/dev/test && bash ./run-pytests-basic-env.sh && bash ./run-pytests-basic-pytorch.sh && bash ./run-pytests-basic-tf2.sh" 

        exit_status=$(docker wait ${CONTAINER_NAME})

        if [ $exit_status -ne 0 ];
        then
          echo "Test fail!"
          docker logs ${CONTAINER_NAME}
        fi
        docker container rm ${CONTAINER_NAME} -f
        exit $exit_status

