imageName: intelanalytics/bigdl-ppml-trusted-dl-serving-gramine-ref:2.4.0
nfsServerIp: your_nfs_server_ip
nfsPath: a_nfs_shared_folder_path_on_the_server
TEEMode: sgx # sgx, tdx or native
PCCSUrl: your_pccs_url # please set to "" for native TEEMode
backendNum: 10
modelName: BERT_LARGE
inferencePort: 8085
managementPort: 8081
metricsPort: 8082
backendPort: 9000
istioTLSEnabled: false # istio TLS protects pod communication between backend and frontend, pls make sure istio has been installed in your cluster before enabling
modelDecryption: true
aesKey: your_key_file_name
tlsEnable: true
savedOnDisk: true
securedDir: your_secure_dir
