name: 'Run Orca Tutorial Xshards'
description: 'Run Orca Tutorial Xshards'
runs:
  using: "composite"
  steps:
    - name: Setup Env
      shell: bash
      run: |
        apt-get update
        apt-get install wget

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools==58.0.4
        
    - name: Run Test
      shell: bash
      run: |
        conda remove -n orca-tutorial-xshards-py37 -y --all
        conda create -n orca-tutorial-xshards-py37 -y python==3.7.10 setuptools==58.0.4 -c ${GONDOLIN_CONDA_CHANNEL} --override-channels
        conda info -e
        source activate orca-tutorial-xshards-py37
        pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib bigdl-dllib-spark3 bigdl-orca pyspark bigdl-orca-spark3 bigdl-chronos bigdl-chronos-spark3 bigdl-friesian bigdl-friesian-spark3
        pip uninstall -y intel-tensorflow
        pip uninstall -y tensorflow
        pip install -i https://pypi.org/simple --pre --upgrade bigdl-orca-spark3[ray]
        pip install tensorflow==1.15.0
        pip install sklearn
        pip install pandas
        pip install jep==3.9.0
        pip install cloudpickle
        
        wget https://raw.githubusercontent.com/analytics-zoo/BigDL/main/python/test/python-requirements/requirements-orca-python-ray.txt -O ${{ github.workspace }}/requirements-orca-python-ray.txt
        pip uninstall -r ${{ github.workspace }}/requirements-orca-python-ray.txt -y
        pip install -i ${GONDOLIN_PIP_MIRROR} --trusted-host ${GONDOLIN_TRUSTED_HOST} -r ${{ github.workspace }}/requirements-orca-python-ray.txt
        export SPARK_LOCAL_HOSTNAME=localhost
        export FTP_URI=${FTP_URI}
        chmod a+x python/orca/dev/test/run-tutorial-xshards.sh
        python/orca/dev/test/run-tutorial-xshards.sh

        source deactivate
        conda remove -n orca-tutorial-xshards-py37 -y --all
      env:
        BIGDL_ROOT: ${{ github.workspace }}