site_name: BigDL Project
extra_css: [extra.css]
theme: null
theme_dir: readthedocs
repo_name: 'GitHub '
repo_url: 'https://github.com/intel-analytics/BigDL'


pages:
- Overview: index.md 
- Releases: release.md
- Getting Started: getting-started.md
- User Guide: 
  - Install: UserGuide/install.md
  - Run : UserGuide/run.md
  - Examples: UserGuide/examples.md
  - More Resources: UserGuide/resources.md
- Python Support: 
  - Install: PythonSupport/python-install.md
  - Run: PythonSupport/python-run.md
  - Examples: PythonSupport/python-examples.md
  - More Examples and Tutorials: PythonSupport/python-resources.md
  - Tensorflow Support: PythonSupport/tensorflow-support.md
- Programming Guide:
  - Scala Docs: APIdocs/scaladoc.md
  - Python API Docs: APIdocs/python-api-doc.md
  - Data: APIdocs/Data/merged-Data.md
  - Model:
    - Sequential Model: APIdocs/Model/Sequential.md
    - Functional API: APIdocs/Model/Functional.md
    - Module API: APIdocs/Model/ModuleAPI.md
  - Layers: 
    - Containers:  APIdocs/Layers/Containers/merged-Containers.md
    - Simple Layers: APIdocs/Layers/Simple-Layers/merged-Simple-Layers.md
    - Convolution Layers: APIdocs/Layers/Convolution-Layers/merged-Convolution-Layers.md
    - Pooling Layers:  APIdocs/Layers/Pooling-Layers/merged-Pooling-Layers.md
    - Linear Layers:  APIdocs/Layers/Linear-Layers/merged-Linear-Layers.md
    - Non-linear Activations: APIdocs/Layers/Non-linear-Activations/merged-Non-linear-Activations.md
    - Embedding Layers: APIdocs/Layers/Embedding-Layers/merged-Embedding-Layers.md
    - Merge/Split Layers: APIdocs/Layers/MergeSplit-Layers/merged-MergeSplit-Layers.md
    - Math Layers: APIdocs/Layers/Math-Layers/merged-Math-Layers.md
    - Padding Layers: APIdocs/Layers/Padding-Layers/merged-Padding-Layers.md
    - Normalization Layers:  APIdocs/Layers/Normalization-Layers/merged-Normalization-Layers.md
    - Dropout Layers: APIdocs/Layers/Dropout-Layers/merged-Dropout-Layers.md
    - Distance Layers: APIdocs/Layers/Distance-Layers/merged-Distance-Layers.md
    - Recurrent Layers:  APIdocs/Layers/Recurrent-Layers/merged-Recurrent-Layers.md
    - Utilities: APIdocs/Layers/Utilities/merged-Utilities.md
  - Losses: APIdocs/Losses/merged-Losses.md
  - Initalizers: APIdocs/Initializers/merged-Initializers.md
  - Regularizers: APIdocs/Regularizers/merged-Regularizers.md
  - Optimization: 
    - Optimizer: APIdocs/Optimizers/DistriOptimizer.md
    - Optimization Algorithms: APIdocs/Optimizers/Optim-Methods/merged-Optim-Methods.md
    - Triggers: APIdocs/Optimizers/Triggers.md
    - Resume Training: APIdocs/Optimizers/ResumeTraining.md
  - Metrics:  APIdocs/Metrics/merged-Metrics.md
  - Visualization: ProgrammingGuide/visualization-with-tensorboard.md
  - MLPipeline: APIdocs/MLPipeline/merged-MLPipeline.md
- Powered by: powered-by.md
- Known Issues: known-issues.md
