apiVersion: v1
kind: Service
metadata:
  name: fl-server
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 8980
    - name: rpcvfl
      port: 8981
  selector:
    app: fldemo
    component: flserver
