{{- if .Values.init.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "friesian-serving.feature.fullname" . }}-init
  namespace: {{ template "friesian-serving.namespace" . }}
  labels:
    app: {{ template "friesian-serving.name" . }}-feature
    {{ include "friesian-serving.labels" . | nindent 4 }}
    {{- if .Values.feature.labels }}
    {{ toYaml .Values.feature.labels | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if .Values.feature.annotations }}
    {{ toYaml .Values.feature.annotations | nindent 4 }}
    {{- end }}
data:
  config_feature.yaml: |
    {{- if .Values.redis.enabled }}
      {{- if .Values.redis.sentinel.enabled }}
    redisType: sentinel
    redisSentinelMasterURL: {{ printf "%s-headless" (include "friesian-serving.redis.fullname" .) }}:26379
    redisSentinelMasterName: {{ .Values.redis.sentinel.masterSet }}
      {{- else }}
    redisUrl: {{ include "friesian-serving.redis.fullname" . }}:6379
      {{- end }}
    {{- end }}
    {{- with .Values.init.feature.config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.init.feature.resourcePath }}
    {{- if .initialUserDataPath }}
    initialUserDataPath: /resources/{{ .initialUserDataPath }}
    {{- end }}
    {{- if .initialItemDataPath }}
    initialItemDataPath: /resources/{{ .initialItemDataPath }}
    {{- end }}
    {{- end }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "friesian-serving.feature.fullname" . }}-init
  namespace: {{ template "friesian-serving.namespace" . }}
  labels:
    app: {{ template "friesian-serving.name" . }}-feature
    {{ include "friesian-serving.labels" . | nindent 4 }}
    {{- if .Values.feature.labels }}
    {{ toYaml .Values.feature.labels | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "10"
    {{- if .Values.feature.annotations }}
    {{ toYaml .Values.feature.annotations | nindent 4 }}
    {{- end }}
spec:
  template:
    spec:
      containers:
      - name: feature-init
        image: "{{ .Values.init.image.repository }}:{{ .Values.init.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.init.image.pullPolicy }}
        args: ["feature-init", "-c", "mnt/config_feature.yaml"]
        volumeMounts:
        - name: config
          mountPath: /opt/work/mnt
        - name: resources
          mountPath: /resources
      volumes:
      - name: config
        configMap:
          name: {{ include "friesian-serving.feature.fullname" . }}-init
      - name: resources
        persistentVolumeClaim:
          claimName: {{ .Values.resourcePVCName }}
      restartPolicy: Never
  backoffLimit: 10
{{- end }}
