name: BigDL Release Scala

on:
  pull_request:
  
  workflow_dispatch:


permissions:
  contents: read
  packages: write

jobs:
  bigdl-release-scala:
    runs-on: [self-hosted, ubuntu-20.04-lts, Bree]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Maven clean deploy
      run: |
        set -x
        set -e
        export TIMESTAMP=`date '+%Y%m%d'`
        export JAVA_HOME=/opt/jdk1.8.0_152
        export JRE_HOME=${JAVA_HOME}/jre
        export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib:$CLASSPATH
        export JAVA_PATH=${JAVA_HOME}/bin:${JRE_HOME}/bin
        export PATH=${JAVA_PATH}:$PATH
        export PATH=/opt/work/apache-maven-3.6.3/bin:$PATH
        cp scala/pom.xml scala/pom.xml.origin
        cp scala/common/spark-version/pom.xml scala/common/spark-version/pom.xml.origin
        cp scala/common/spark-version/3.0/pom.xml scala/common/spark-version/3.0/pom.xml.origin
        cp scala/dllib/pom.xml scala/dllib/pom.xml.origin
        cp scala/orca/pom.xml scala/orca/pom.xml.origin
        cp scala/friesian/pom.xml scala/friesian/pom.xml.origin
        cp scala/grpc/pom.xml scala/grpc/pom.xml.origin
        cp scala/serving/pom.xml scala/serving/pom.xml.origin
        cp scala/ppml/pom.xml scala/ppml/pom.xml.origin
        cp scala/assembly/pom.xml scala/assembly/pom.xml.origin

