name: Chronos PRVN Python Spark3.1

# Cancel previous runs in the PR when you push new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

# Controls when the action will run. 
on:
  # Triggers the workflow on merge events for nano/orca change
  push:
    branches: [ main ]
    paths:
      - 'python/nano/src/**'
      - 'python/orca/src/bigdl/orca/automl/**'
      - 'python/orca/src/bigdl/orca/data/**'
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    paths:
      - 'python/chronos/src/**'
      - 'python/chronos/test/**'
      - '.github/workflows/chronos-prvn-python-spark31.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  chronos-PRVN-spark31-py37-part1:
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up Maven
        uses: ./.github/actions/maven-setup-action
      - name: Set up Chronos Env
        uses: ./.github/actions/chronos/setup-env/setup-chronos-python37
      - name: Activate Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source activate chronos-py37-env
      - name: Run Chronos python test
        uses: ./.github/actions/chronos/chronos-prvd-spark31-action/part1
      - name: Remove Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source deactivate
          conda remove -n chronos-py37-env -y --all

  chronos-PRVN-spark31-py37-part2:
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up Maven
        uses: ./.github/actions/maven-setup-action
      - name: Set up Chronos Env
        uses: ./.github/actions/chronos/setup-env/setup-chronos-python37
      - name: Activate Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source activate chronos-py37-env
      - name: Run Chronos python test
        uses: ./.github/actions/chronos/chronos-prvd-spark31-action/part2
      - name: Remove Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source deactivate
          conda remove -n chronos-py37-env -y --all

  chronos-PRVN-spark31-py37-part3:
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up Maven
        uses: ./.github/actions/maven-setup-action
      - name: Set up Chronos Env
        uses: ./.github/actions/chronos/setup-env/setup-chronos-python37
      - name: Activate Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source activate chronos-py37-env
      - name: Run Chronos python test
        uses: ./.github/actions/chronos/chronos-prvd-spark31-action/part3
      - name: Remove Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source deactivate
          conda remove -n chronos-py37-env -y --all

  chronos-PRVN-spark31-py37-part4:
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up Maven
        uses: ./.github/actions/maven-setup-action
      - name: Set up Chronos Env
        uses: ./.github/actions/chronos/setup-env/setup-chronos-python37
      - name: Activate Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source activate chronos-py37-env
      - name: Run Chronos python test
        uses: ./.github/actions/chronos/chronos-prvd-spark31-action/part4
      - name: Remove Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source deactivate
          conda remove -n chronos-py37-env -y --all

  chronos-PRVN-spark31-py38-part1:
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up Maven
        uses: ./.github/actions/maven-setup-action
      - name: Set up Chronos Env
        uses: ./.github/actions/chronos/setup-env/setup-chronos-python38
      - name: Activate Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source activate chronos-py38-env
      - name: Run Chronos python test
        uses: ./.github/actions/chronos/chronos-prvd-spark31-action/part1
      - name: Remove Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source deactivate
          conda remove -n chronos-py38-env -y --all

  chronos-PRVN-spark31-py38-part2:
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up Maven
        uses: ./.github/actions/maven-setup-action
      - name: Set up Chronos Env
        uses: ./.github/actions/chronos/setup-env/setup-chronos-python38
      - name: Activate Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source activate chronos-py38-env
      - name: Run Chronos python test
        uses: ./.github/actions/chronos/chronos-prvd-spark31-action/part2
      - name: Remove Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source deactivate
          conda remove -n chronos-py38-env -y --all

  chronos-PRVN-spark31-py38-part3:
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up Maven
        uses: ./.github/actions/maven-setup-action
      - name: Set up Chronos Env
        uses: ./.github/actions/chronos/setup-env/setup-chronos-python38
      - name: Activate Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source activate chronos-py38-env
      - name: Run Chronos python test
        uses: ./.github/actions/chronos/chronos-prvd-spark31-action/part3
      - name: Remove Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source deactivate
          conda remove -n chronos-py38-env -y --all

  chronos-PRVN-spark31-py38-part4:
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up Maven
        uses: ./.github/actions/maven-setup-action
      - name: Set up Chronos Env
        uses: ./.github/actions/chronos/setup-env/setup-chronos-python38
      - name: Activate Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source activate chronos-py38-env
      - name: Run Chronos python test
        uses: ./.github/actions/chronos/chronos-prvd-spark31-action/part4
      - name: Remove Chronos Env
        if: ${{ always() }}
        shell: bash
        run: |
          source deactivate
          conda remove -n chronos-py38-env -y --all
