name: Chronos Install Option On Python3.8

# Cancel previous runs in the PR when you push new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/chronos-install-option-py38-test.yml'
  workflow_dispatch:

jobs:
  pytorch option:
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: ./.github/actions/jdk-setup-action
