name: Nightly Build Docker Publish BigDL/BigDL-K8S

on:
  schedule:
    - cron: '0 17 * * *'
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      tag:
        description: 'e.g. 2.1.0-SNAPSHOT'
        required: true
        default: 'latest'
        type: string

jobs:
  deploy-docker:

    runs-on: [self-hosted, Shire]
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: set env
      run: |
        if [ -n "${{inputs.tag}}" ]; then  export TAG=${{inputs.tag}};  else export TAG=latest; fi
    - name: docker login
      run: |
        docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
    - name: docker deploy bigdl
      run: |
        echo ${TAG}
        export IMAGE=intelanalytics/bigdl
        cd docker/bigdl
        echo "########################################"
        echo "################# bigdl 3.1.2 #######"
        echo "########################################"
    - name: docker deploy bigdl-k8s
      run: |
        cd docker/bigdl-k8s
        export IMAGE=intelanalytics/bigdl-k8s
        echo ${TAG}
        echo "########################################"
        echo "################# bigdl-k8s 3.1.2 #######"
        echo "########################################"
