name: Nightly Build Docker Publish BigDL/BigDL-K8S

on:
  schedule:
    - cron: '0 17 * * *'
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      TAG:
        description: 'e.g. 2.1.0-SNAPSHOT'
        required: false
        default: 'latest'
        type: string
        
jobs:
  deploy-docker:

    runs-on: [self-hosted, Shire]
    permissions:
      contents: read
      packages: write

    steps:
    - name: docker login
      run: |
        echo ${TAG}
        docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
    - name: docker deploy bigdl
      run: |
        export IMAGE=intelanalytics/bigdl-k8s
        cd docker/bigdl-k8s
        echo "########################################"
        echo "################# bigdl 3.1.2 #######"
        echo "########################################"
        pwd
    - name: docker deploy bigdl-k8s
      run: |
        cd -
        cd docker/bigdl-k8s
        pwd
        echo "########################################"
        echo "################# bigdl-k8s 3.1.2 #######"
        echo "########################################"
