name: Nightly Build Docker Publish BigDL-PPML-test

on:
  # schedule:
  #   - cron: '0 17 * * *'
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      artifact:
        description: 'select which job to run("ALL" will make all jobs run)'
        required: true
        default: 'latest'
        type: choice
        options:
        - all
        - bigdl-ppml-trusted-big-data-ml-python-graphene
        - bigdl-ppml-trusted-realtime-ml-scala-graphene
        - bigdl-ppml-trusted-big-data-ml-scala-occlum
        - bigdl-ppml-trusted-realtime-ml-scala-occlum
      tag:
        description: 'e.g. 2.1.0-SNAPSHOT'
        required: true
        default: 'latest'
        type: string
  

jobs:
  docker-publish-ppml:
    runs-on: [self-hosted, Shire]
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: |
        docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
    - name: Set the variable
      env:
        DEFAULT_TAG: 'latest'
        DEFAULT_ARTIFACT: 'ALL'
      run: |
        echo "TAG=${{ github.event.inputs.tag || env.DEFAULT_TAG }} " >> $GITHUB_ENV
        echo "ARTIFACT=${{ github.event.inputs.artifact || env.DEFAULT_ARTIFACT }}" >> $GITHUB_ENV
    - name: bigdl-ppml-trusted-big-data-ml-python-graphene
      run: |
        echo $ARTIFACT && echo $TAG
        if [[ "$ARTIFACT" == bigdl-ppml-trusted-realtime-ml-scala-graphene || "$ARTIFACT" == ALL ]]; then
        echo "########################################"
        echo "####### big-data-ml-python-graphene ####"
        echo "########################################"
        fi
    - name: bigdl-ppml-trusted-realtime-ml-scala-graphene
      run: |
        echo $ARTIFACT && echo $TAG
        if [[ "$ARTIFACT" == bigdl-ppml-trusted-realtime-ml-scala-graphene || "$ARTIFACT" == ALL ]]; then
        echo "########################################"
        echo "####### realtime-ml-scala-graphene #####"
        echo "########################################"
        cd ppml/trusted-realtime-ml/scala/docker-graphene/
        fi
    - name: bigdl-ppml-trusted-big-data-ml-scala-occlum
      run: |
        echo $ARTIFACT && echo $TAG
        if [[ "$ARTIFACT" == bigdl-ppml-trusted-big-data-ml-scala-occlum || "$ARTIFACT" == ALL ]]; then
        echo "########################################"
        echo "####### big-data-ml-scala-occlum  ######"
        echo "########################################"
        fi
    - name: bigdl-ppml-trusted-realtime-ml-scala-occlum
      run: |
        echo $ARTIFACT && echo $TAG
        if [[ "$ARTIFACT" == bigdl-ppml-trusted-realtime-ml-scala-occlum || "$ARTIFACT" == ALL ]]; then
        echo "########################################"
        echo "####### realtime-ml-scala-occlum  ######"
        echo "########################################"
        fi
