name: Nightly Build Docker Publish BigDL-PPML

on:
  schedule:
    - cron: '0 17 * * *'
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      ARTIFACT:
        description: 'select which job to run("ALL" will make all jobs run)'
        required: true
        default: 'latest'
        type: choice
        options:
        - ALL
        - pythonGramine
        - pythonGraphene
        - scalaGraphene
        - bigdataScalaOcclum
        - realtimeScalaOcclum
env:
  ALL: 0
  pythonGramine: 1
  pythonGraphene: 2
  scalaGraphene: 3
  bigdataScalaOcclum: 4
  realtimeScalaOcclum: 5
  

jobs:
  docker-login:
    runs-on: [self-hosted, Shire]
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: |
        docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
        echo ${${{inputs.ARTIFACT}}}



  big-data-ml-python-gramine:
    if: ${${{inputs.ARTIFACT}}} == 1
    runs-on: [self-hosted, Shire]
    permissions:
      contents: read
      packages: write

    steps:
    - name: docker build bigdl-ppml-trusted-big-data-ml-python-gramine
      run: |
        echo "########################################"
        echo "####### big-data-ml-python-gramine ####"
        echo "########################################"
        export image=intelanalytics/bigdl-ppml-trusted-big-data-ml-python-gramine
        echo ${image}
        echo ${${{inputs.ARTIFACT}}}




  big-data-ml-python-graphene:
    if: ${${{inputs.ARTIFACT}}} == 2
    runs-on: [self-hosted, Shire]
    permissions:
      contents: read
      packages: write

    steps:
    - name: docker build bigdl-ppml-trusted-big-data-ml-python-graphene
      run: |
        echo "########################################"
        echo "####### big-data-ml-python-graphene ####"
        echo "########################################"
        export image=intelanalytics/bigdl-ppml-trusted-big-data-ml-python-graphene
        echo ${image}
        echo ${${{inputs.ARTIFACT}}}


  realtime-ml-scala-graphene:
    if: ${${{inputs.ARTIFACT}}} == 3
    runs-on: [self-hosted, Shire]
    permissions:
      contents: read
      packages: write
    steps:
    - name: docker build bigdl-ppml-trusted-big-data-ml-python-graphene
      run: |
        echo "########################################"
        echo "####### realtime-ml-scala-graphene #####"
        echo "########################################"
        export image=intelanalytics/bigdl-ppml-trusted-realtime-ml-scala-graphene
        echo ${image}
        echo ${${{inputs.ARTIFACT}}}



  big-data-ml-scala-occlum:
    if: ${${{inputs.ARTIFACT}}} == 4
    runs-on: [self-hosted, Shire]
    permissions:
      contents: read
      packages: write
    steps:
    - name: docker build bigdl-ppml-trusted-big-data-ml-scala-occlum
      run: |
        echo "########################################"
        echo "####### big-data-ml-scala-occlum  ######"
        echo "########################################"
        export image=intelanalytics/bigdl-ppml-trusted-realtime-ml-scala-graphene
        echo ${image}
        echo ${${{inputs.ARTIFACT}}}
        
  
  trusted-realtime-ml-scala-occlum:
    if: ${${{inputs.ARTIFACT}}} == 5
    runs-on: [self-hosted, Shire]
    permissions:
      contents: read
      packages: write
    steps:
    - name: bigdl-ppml-trusted-realtime-ml-scala-occlum
      run: |
        echo "########################################"
        echo "####### realtime-ml-scala-occlum  ######"
        echo "########################################"
        export image=intelanalytics/bigdl-ppml-trusted-realtime-ml-scala-occlum
        echo ${image}
        echo ${${{inputs.ARTIFACT}}}

