name: Friesian Docker Build

on:
  #  push:
  #    paths:
  #      - 'scala/friesian/**'
  #      - '.github/actions/friesian-docker-build-action/action.yml'
  #  pull_request:
  #    branches: [ main ]
  #    paths:
  #      - 'scala/friesian/**'
  #      - '.github/actions/friesian-docker-build-action/action.yml'
  #  schedule:
  #    - cron: '0 12 * * *' # GMT time, 12:00 GMT == 20:00 China
  workflow_dispatch:
    inputs:
      tag:
        description: 'docker image tag (e.g. 2.1.0-SNAPSHOT)'
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  friesian-docker-build:
    runs-on: [ self-hosted, Shire ]
    steps:
      - uses: actions/checkout@v3
      - name: set env
        run: |
          echo "TAG=${{github.event.inputs.tag||'latest'}}" >> $GITHUB_ENV
      - name: Set up JDK8
        uses: ./.github/actions/jdk-setup-action
      - name: Build docker
        uses: ./.github/actions/friesian-docker-build-action

