name: license-scan

on:
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  schedule:
    - cron: '0 3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{ secrets.FOSSAAPIKEY }}
          
      - name: "Run FOSSA Test"
        uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{ secrets.FOSSAAPIKEY }}
          run-tests: true

      - name: Create Job Badge
        if: ${{ always() }}
        uses: ./.github/actions/create-job-status-badge
        with:
          secret: ${{ secrets.GIST_SECRET }}
          gist-id: f91eb10af4d9dbe216ba0f0da71cace9
          isSelfHostedRunner: false
          file-name: fossa-scan.json
          type: job
          job-name: fossa-scan

  create-workflow-badge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: create workflow badge
      if: ${{ always() }}
      uses: ./.github/actions/create-job-status-badge
      with:
        secret: ${{ secrets.GIST_SECRET }}
        gist-id: 966d4c0bf23c67662120d1bf4b1c88dc
        file-name: license-scan.json
        type: workflow
