name: license-scan

on:
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  schedule:
    - cron: '0 3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{ secrets.FOSSAAPIKEY }}
          
      - name: "Run FOSSA Test"
        uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{ secrets.FOSSAAPIKEY }}
          run-tests: true

      - name: "Set time variable"
        run: |
          export NOW=$( date '+%F_%H:%M:%S' )
          echo "TIME=${NOW}" >> $GITHUB_ENV
          
      - name: "Create Badge"
        uses: schneegans/dynamic-badges-action@v1.4.0
        with:
          auth: ${{ secrets.GIST_KEY }}
          gistID: 23967bd68c41e388292692ae5dea3aa3
          filename: license-scan.json
          label: Time
          message: is ${{ env.TIME }}
          valColorRange: ${{ env.TIME }}
          maxColorRange: 100
          minColorRange: 0