name: LLM Nightly Tests on Windows

# Cancel previous runs in the PR when you push new commits
concurrency:
  group: ${{ github.workflow }}-llm-nightly-test-win-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths:
      - ".github/workflows/llm-nightly-test-windows.yml"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/llm-nightly-test-windows.yml"
  workflow_dispatch:
  workflow_call:

env:
  MODEL_DIR: ../
  INT4_CKPT_DIR: ./llm/ggml-actions/stable
  LLAMA_INT4_CKPT_PATH: ./llm/ggml-actions/stable/bigdl_llm_llama_7b_q4_0.bin
  GPTNEOX_INT4_CKPT_PATH: ./llm/ggml-actions/stable/bigdl_llm_redpajama_7b_q4_0.bin
  BLOOM_INT4_CKPT_PATH: ./llm/ggml-actions/stable/bigdl_llm_bloom_7b_q4_0.bin
  STARCODER_INT4_CKPT_PATH: ./llm/ggml-actions/stable/bigdl_llm_santacoder_1b_q4_0.bin
  ORIGINAL_CHATGLM2_6B_PATH: ./llm/chatglm2-6b/
  ORIGINAL_REPLIT_CODE_PATH: ./llm/replit-code-v1-3b/
  ORIGINAL_WHISPER_TINY_PATH: ./llm/whisper-tiny/
  SPEECH_DATASET_PATH: ./llm/datasets/librispeech_asr_dummy
  LLM_DIR: ./llm


jobs:
  llm-cpp-build:
    uses: ./.github/workflows/llm-binary-build.yml
  llm-nightly-test-windows:
    runs-on: ["self-hosted", "Windows"]
    needs: llm-cpp-build
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools==58.0.4
          python -m pip install --upgrade wheel
      - name: Download llm binary
        uses: ./.github/actions/llm/download-llm-binary
      - name: Install BigDL-llm
        shell: bash
        run: |
          pip install requests
          bash python/llm/dev/release_default_windows.sh default false
          whl_name=$(ls python/llm/dist)
          pip install -i https://pypi.python.org/simple "python/llm/dist/${whl_name}[all]"
          pip install pytest