name: LLM Unit Tests Basic on Linux

# Cancel previous runs in the PR when you push new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'python/llm/**'
      - '.github/workflows/llm_unit_tests_basic_linux.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'python/llm/**'
      - '.github/workflows/llm_unit_tests_basic_linux.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  llm-unit-test-basic-linux:
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools==58.0.4
          python -m pip install --upgrade wheel

      - name: Run LLM-init test
        shell: bash
        run: |
          $CONDA_HOME/bin/conda env remove -y -n bigdl-init-llm || true
          $CONDA_HOME/bin/conda create -n bigdl-init-llm -y python==3.9 setuptools==58.0.4 -c ${GONDOLIN_CONDA_CHANNEL} --override-channels
          source $CONDA_HOME/bin/activate bigdl-init-llm
          $CONDA_HOME/bin/conda info
          pip install requests
          bash python/llm/dev/release_default_linux.sh default false
          pip install -i https://pypi.python.org/simple python/llm/dist/bigdl_llm*.whl
          source $CONDA_HOME/bin/deactivate
          $CONDA_HOME/bin/conda remove -n bigdl-init-llm --all
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
      
      - name: Run LLM naive installation test
        shell: bash
        run: |
          $CONDA_HOME/bin/conda env remove -y -n bigdl-init-llm || true
          $CONDA_HOME/bin/conda create -n bigdl-init-llm -y python==3.9 setuptools==58.0.4 -c ${GONDOLIN_CONDA_CHANNEL} --override-channels
          source $CONDA_HOME/bin/activate bigdl-init-llm
          $CONDA_HOME/bin/conda info
          pip install requests
          bash python/llm/dev/release_default_linux.sh default false
          whl_name=$(ls python/llm/dist)
          pip install -i https://pypi.python.org/simple "python/llm/dist/${whl_name}[all]"
          pip install pytest
          bash python/llm/test/run-llm-basic-tests.sh
          source $CONDA_HOME/bin/deactivate
          $CONDA_HOME/bin/conda remove -n bigdl-init-llm --all
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
