name: Manually Build

on:
  pull_request:
  workflow_dispatch:
    inputs:
      artifact:
        description: 'select which job to run("all" will make all jobs run)'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - bigdl-ppml-gramine-base
        - bigdl-ppml-trusted-deep-learning-gramine-base
        - bigdl-ppml-trusted-deep-learning-gramine-ref
        - bigdl-ppml-trusted-dl-serving-gramine-base
        - bigdl-ppml-trusted-dl-serving-gramine-ref
        - bigdl-ppml-trusted-big-data-ml-python-gramine
        - bigdl-ppml-trusted-big-data-ml-python-gramine-noattest
        - bigdl-ppml-trusted-big-data-ml-python-graphene
        - bigdl-ppml-trusted-big-data-ml-scala-occlum
        - bigdl-ppml-trusted-big-data-ml-scala-occlum-production
        - bigdl-ppml-trusted-big-data-ml-scala-occlum-production-customer
        - bigdl-ppml-trusted-realtime-ml-scala-graphene
        - bigdl-ppml-trusted-realtime-ml-scala-occlum
        - bigdl-ppml-kmsutil
        - bigdl-ppml-pccs
        - bigdl-ppml-trusted-python-toolkit-base
        - bigdl-ppml-trusted-python-toolkit-ref
        - bigdl-ppml-trusted-bigdata-gramine
        - bigdl-kms
      tag:
        description: 'docker image tag (e.g. 2.1.0-SNAPSHOT)'
        required: true
        default: 'latest'
        type: string

env:
  TAG: ${{ github.event.inputs.tag }}

permissions:
  contents: read
  packages: write

jobs:

  bigdl-ppml-trusted-deep-learning-gramine-base:
    runs-on: [self-hosted, vRA]
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: |
        docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
    - name: bigdl-ppml-trusted-deep-learning-gramine-base
      run: |
        echo "##############################################################"
        echo "####### bigdl-ppml-trusted-deep-learning-gramine-base ########"
        echo "##############################################################"
        export base_image=intelanalytics/bigdl-ppml-gramine-base
        export image=intelanalytics/bigdl-ppml-trusted-deep-learning-gramine-base
        export TAG=2.3.0-SNAPSHOT
        cd ppml/trusted-deep-learning/base
        sudo docker build \
          --no-cache=true \
          --build-arg http_proxy=${HTTP_PROXY} \
          --build-arg https_proxy=${HTTPS_PROXY} \
          --build-arg no_proxy=${NO_PROXY} \
          --build-arg BASE_IMAGE_NAME=${base_image} \
          --build-arg BASE_IMAGE_TAG=${TAG} \
          -t ${image}:${TAG} -f ./Dockerfile .
        sudo docker push ${image}:${TAG}
        sudo docker tag ${image}:${TAG} 10.239.45.10/arda/${image}:${TAG}
        sudo docker push 10.239.45.10/arda/${image}:${TAG}
        sudo docker rmi -f ${image}:${TAG} 10.239.45.10/arda/${image}:${TAG}


 
