name: Nano Unit Tests Tensorflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'python/nano/**'
      - '.github/workflows/nano_unit_tests_tensorflow.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  nano-unit-test-tensorflow:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        python-version: ["3.7"]
        tf-version: [
          "intel-tensorflow==2.8.0 keras==2.8.0 tensorflow-estimator==2.8.0",
          ""
          ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools==58.0.4
          python -m pip install --upgrade wheel
          sudo apt-get install openmpi-bin openmpi-doc libopenmpi-dev


      - name: Run tensorflow unit tests (OpenVINO)
        shell: bash
        run: |
          $CONDA/bin/conda create -n openvino-tensorflow -y python==3.7.10 setuptools=58.0.4
          source $CONDA/bin/activate openvino-tensorflow
          $CONDA/bin/conda info
          bash python/nano/dev/build_and_install.sh linux default false tensorflow
          if [ ! -z "${{matrix.tf-version}}" ]; then
            pip install ${{matrix.tf-version}}
          fi
          pip install pytest
          pip install openvino-dev
          pip install numpy==1.21.6
          source bigdl-nano-init
          bash python/nano/test/run-nano-tf-openvino-tests.sh
          source $CONDA/bin/deactivate
          $CONDA/bin/conda remove -n openvino-tensorflow --all
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}