name: Nano Nightly Test

# Controls when the action will run.
on:
  schedule:
    - cron: '00 17 * * *' # GMT time, 17:00 GMT == 01:00 China
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/nano-nightly-test.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Nano-PyTorch-UT-Test:
    runs-on: [ "ubuntu-20.04" ]

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Nano PyTorch Env
      uses: ./.github/actions/nano/setup-pytorch-env
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run Nano PyTorch Test
      uses: ./.github/actions/nano/pytorch-test
    - name: Remove Nano PyTorch Env
      uses: ./.github/actions/nano/remove-pytorch-env

  Nano-Tensorflow-UT-Test:
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Nano Tensorflow Env
      uses: ./.github/actions/nano/setup-tensorflow-env
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run Nano Tensorflow Test
      uses: ./.github/actions/nano/tensorflow-test
    - name: Remove Nano Tensorflow Env
      uses: ./.github/actions/nano/remove-tensorflow-env
