name: Nano Unit Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  nano-unit-test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        python-version: ["3.7"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools==58.0.4
          python -m pip install --upgrade wheel

      - name: Build Nano whl
        run: bash python/nano/dev/release_default_linux.sh default false

      - name: Run Nano-init test
        shell: bash
        run: |
          $CONDA/bin/conda create -n bigdl-init -y python==3.7.10 setuptools==58.0.4
          source $CONDA/bin/activate bigdl-init
          $CONDA/bin/conda info
          whl_name=`ls python/nano/src/dist/`;pip install python/nano/src/dist/$whl_name[pytorch]
          source bigdl-nano-init
          if [ 0"$LD_PRELOAD" = "0" ]; then
            exit 1
          else
            echo "Set environment variable successfully."
          fi
          source $CONDA/bin/deactivate
          if [ ! 0"$LD_PRELOAD" = "0" ]; then
            exit 1
          else
            echo "Unset environment variable successfully while deactivating conda environment."
          fi
          source $CONDA/bin/activate bigdl-init
          if [ 0"$LD_PRELOAD" = "0" ]; then
            exit 1
          else
            echo "Setup environment variable successfully while activating conda environment."
          fi
          pip uninstall -y bigdl-nano
          source $CONDA/bin/deactivate
          $CONDA/bin/conda remove -n bigdl-init --all
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

      - name: Run ray PyTorch unit tests
        shell: bash
        run: |
          $CONDA/bin/conda create -n ray-pytorch -y python==3.7.10 setuptools=58.0.4
          source $CONDA/bin/activate ray-pytorch
          $CONDA/bin/conda info
          whl_name=`ls python/nano/src/dist/`;pip install python/nano/src/dist/$whl_name[pytorch]
          pip install pytest
          pip install ray[default]==1.11.0 prometheus_client==0.13.0
          source bigdl-nano-init
          bash python/nano/test/run-nano-pytorch-ray-tests.sh
          source $CONDA/bin/deactivate
          $CONDA/bin/conda remove -n ray-pytorch --all
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

      - name: Run ray TF unit tests
        shell: bash
        run: |
          $CONDA/bin/conda create -n ray-tf -y python==3.7.10 setuptools=58.0.4
          source $CONDA/bin/activate ray-tf
          $CONDA/bin/conda info
          whl_name=`ls python/nano/src/dist/`;pip install python/nano/src/dist/$whl_name[tensorflow]
          pip install pytest
          pip install ray[default]==1.11.0 prometheus_client==0.13.0
          source bigdl-nano-init
          bash python/nano/test/run-nano-tf-ray-tests.sh
          source $CONDA/bin/deactivate
          $CONDA/bin/conda remove -n ray-tf --all
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}

      - name: Run horovod unit tests
        shell: bash
        run: |
          $CONDA/bin/conda create -n horovod-tf -y python==3.7.10 setuptools=58.0.4
          source $CONDA/bin/activate horovod-tf
          $CONDA/bin/conda info
          whl_name=`ls python/nano/src/dist/`;pip install python/nano/src/dist/$whl_name[tensorflow]
          pip install horovod==0.24.2
          pip install pytest
          source bigdl-nano-init
          bash python/nano/test/run-nano-tf-horovod-tests.sh
          source $CONDA/bin/deactivate
          $CONDA/bin/conda remove -n horovod-tf --all
        env:
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}