name: Nano Unit Tests for Notebooks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ add-nano-tensorflow-notebooks-unit-test ]
  pull_request:
    branches: [ main ]
    paths:
      - 'python/nano/**'
      - '.github/workflows/nano_notebooks_tests.yml'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  nano-notebooks-pytorch-test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        python-version: ["3.7"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools==58.0.4
          python -m pip install --upgrade wheel

      - name: Run cifar10 notebooks PyTorch unit tests
        shell: bash
        run: |
            $CONDA/bin/conda create -n notebooks-pytorch -y python==3.7.10 setuptools=58.0.4
            source $CONDA/bin/activate notebooks-pytorch
            $CONDA/bin/conda info
            bash python/nano/dev/build_and_install.sh linux default false pytorch
            source bigdl-nano-init
            pip install -r python/nano/notebooks/pytorch/cifar10/requirements.txt
            bash python/nano/notebooks/pytorch/cifar10/run-nano-notebooks-pytorch-cifar10-tests.sh
            source $CONDA/bin/deactivate
            $CONDA/bin/conda remove -n notebooks-pytorch --all
        env:
            ANALYTICS_ZOO_ROOT: ${{ github.workspace }}


  nano-notebooks-tensorflow-test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        python-version: ["3.7"]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools==58.0.4
          python -m pip install --upgrade wheel

      - name: Run cifar10 notebooks PyTorch unit tests
        shell: bash
        run: |
            $CONDA/bin/conda create -n notebooks-tensorflow -y python==3.7.10 setuptools=58.0.4
            source $CONDA/bin/activate notebooks-tensorflow
            $CONDA/bin/conda info
            bash python/nano/dev/build_and_install.sh linux default false tensorflow
            source bigdl-nano-init
            pip install -r pyhton/nano/notebooks/tensorflow/stanford_dogs/requirements.txt
            source $CONDA/bin/deactivate
            $CONDA/bin/conda remove -n notebooks-tensorflow --all
        env:
            ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
