name: Nightly Build

on:
  pull_request:
  schedule:
    - cron: '0 11 * * *' # GMT time, 11:00 GMT == 19:00 China
  workflow_dispatch:
    inputs:
      artifact:
        description: 'select which job to run("all" will make all jobs run)'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - scala-build
        - python-sourceforge-build
        - docker-bigdl-build
      tag:
        description: 'docker image tag (e.g. 2.1.0-SNAPSHOT)'
        required: true
        default: 'latest'
        type: string
env:
  GIST_ID: 48dbd87983219d4fe264adfea701815a

permissions:
  contents: read
  packages: write

jobs:



  python-sourceforge-build:
    runs-on: [self-hosted, Bree-Test]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install wheel
        pip install twine
    
    - name: Build package
      run: |
        export TIMESTAMP=`date '+%Y%m%d'`
        export PYPI_VERSION=2.3.0
        nb_version=${PYPI_VERSION}b${TIMESTAMP}
        echo ${nb_version}
        apt-get update
        apt-get install sshpass
        #spark2
        ## linux ##
        bash python/dev/release_default_linux_spark2.sh ${nb_version} false false
        
        # upload
        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/dllib/src/dist/bigdl_dllib*-py3-none-manylinux1_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/dllib-py

        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/orca/src/dist/bigdl_orca*-py3-none-manylinux1_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/orca-py

        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/friesian/src/dist/bigdl_friesian*-py3-none-manylinux1_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/friesian-py

        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/chronos/src/dist/bigdl_chronos*-py3-none-manylinux1_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/chronos-py

        #sshpass -p "${SOURCEFORGE_PW}" \
        #scp ./python/serving/src/dist/bigdl_serving*-py2.py3-none-any.whl \
        #intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/cluster-serving-py
        echo "test mac build"
        
        ## mac ##
        bash python/dev/release_default_mac_spark2.sh ${nb_version} false false

        # upload
        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/dllib/src/dist/bigdl_dllib*-py3-none-macosx_10_11_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/dllib-py

        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/orca/src/dist/bigdl_orca*-py3-none-macosx_10_11_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/orca-py

        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/friesian/src/dist/bigdl_friesian*-py3-none-macosx_10_11_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/friesian-py

        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/chronos/src/dist/bigdl_chronos*-py3-none-macosx_10_11_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/chronos-py

        #spark3
        ## linux ##
        bash python/dev/release_default_linux_spark3.sh ${nb_version} false false
        # upload
        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/dllib/src/dist/bigdl_dllib*-py3-none-manylinux1_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/dllib-py-spark3

        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/orca/src/dist/bigdl_orca*-py3-none-manylinux1_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/orca-py-spark3

        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/friesian/src/dist/bigdl_friesian*-py3-none-manylinux1_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/friesian-py-spark3

        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/chronos/src/dist/bigdl_chronos*-py3-none-manylinux1_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/chronos-py-spark3

        ## mac ##
        bash python/dev/release_default_mac_spark3.sh ${nb_version} false false
        # upload
        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/dllib/src/dist/bigdl_dllib*-py3-none-macosx_10_11_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/dllib-py-spark3

        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/orca/src/dist/bigdl_orca*-py3-none-macosx_10_11_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/orca-py-spark3

        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/friesian/src/dist/bigdl_friesian*-py3-none-macosx_10_11_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/friesian-py-spark3

        sshpass -p "${SOURCEFORGE_PW}" \
        scp ./python/chronos/src/dist/bigdl_chronos*-py3-none-macosx_10_11_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/chronos-py-spark3









