name: PR Validation

# Cancel previous runs in the PR when you push new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:

  pull_request:
    branches: [ main ]
    paths:
      - 'scala/serving/pom.xml'
      - 'scala/ppml/pom.xml'
      - 'scala/orca/pom.xml'
      - 'scala/friesian/pom.xml'
      - 'scala/dllib/pom.xml'
      - 'scala/pom.xml'
      - 'scala/friesian/**'
      - '.github/actions/friesian-scala-ut-action/action.yml'
      - 'scala/dllib/**'
      - 'python/dllib/**'
      - '.github/actions/dllib-scala-ut-action/action.yml'
      - 'scala/ppml/**'
      - '.github/actions/ppml-scala-ut-action/action.yml'
      - 'python/orca/**'
      - '.github/actions/orca/**'
      - 'python/ppml/**'
      - '.github/actions/ppml/**'
      - 'python/friesian/**'
      - '.github/actions/friesian/**'
      - '.github/workflows/PR_validation.yml'
      
  push:
    branches: [ main ]
    paths:
      - 'scala/serving/pom.xml'
      - 'scala/ppml/pom.xml'
      - 'scala/orca/pom.xml'
      - 'scala/friesian/pom.xml'
      - 'scala/dllib/pom.xml'
      - 'scala/pom.xml'
      - 'scala/friesian/**'
      - '.github/actions/friesian-scala-ut-action/action.yml'
      - 'scala/dllib/**'
      - 'python/dllib/**'
      - '.github/actions/dllib-scala-ut-action/action.yml'
      - 'scala/ppml/**'
      - '.github/actions/ppml-scala-ut-action/action.yml'
      - 'python/orca/**'
      - '.github/actions/orca/**'
      - 'python/ppml/**'
      - '.github/actions/ppml/**'
      - 'python/friesian/**'
      - '.github/actions/friesian/**'
      - '.github/workflows/PR_validation.yml'

permissions:
  contents: read
  packages: write

jobs:
  changes:
    name: Paths filter
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]
    outputs:
      friesian-pytest: ${{ steps.filter.outputs.friesian-pytest }}
      friesian-example: ${{ steps.filter.outputs.friesian-example }}
      dllib: ${{ steps.filter.outputs.dllib }}
      orca-pytest: ${{ steps.filter.outputs.orca-pytest }}
      orca-pytest-openvino: ${{ steps.filter.outputs.orca-pytest-openvino }}
      orca-tutorial: ${{ steps.filter.outputs.orca-tutorial }}
      orca-example: ${{ steps.filter.outputs.orca-example }}
      ppml: ${{ steps.filter.outputs.ppml }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            friesian-pytest:
              - 'scala/orca/pom.xml'
              - 'scala/friesian/pom.xml'
              - 'scala/dllib/pom.xml'
              - 'scala/pom.xml'
              - 'scala/friesian/**'
              - '.github/actions/friesian-scala-ut-action/action.yml'
              - 'python/friesian/src/**'
              - 'python/friesian/dev/**'
              - 'python/friesian/test/**'
              - '.github/actions/friesian/**'
              - 'python/dev/**'

            friesian-example: 
              - 'scala/orca/pom.xml'
              - 'scala/friesian/pom.xml'
              - 'scala/dllib/pom.xml'
              - 'python/friesian/example/**'
              - 'python/friesian/src/**'
              - 'python/friesian/dev/**'
              - '.github/actions/friesian/**'
              - 'python/orca/src/bigdl/orca/data/**'
              - 'python/dev/**'

            dllib:
              - 'scala/serving/pom.xml'
              - 'scala/ppml/pom.xml'
              - 'scala/orca/pom.xml'
              - 'scala/friesian/pom.xml'
              - 'scala/dllib/pom.xml'
              - 'scala/pom.xml'
              - 'scala/dllib/**'
              - 'python/dllib/**'
              - '.github/actions/dllib-scala-ut-action/action.yml'
              
            ppml:
              - 'scala/serving/pom.xml'
              - 'scala/ppml/pom.xml'
              - 'scala/orca/pom.xml'
              - 'scala/friesian/pom.xml'
              - 'scala/dllib/pom.xml'
              - 'scala/pom.xml'
              - 'scala/ppml/**'
              - '.github/actions/ppml-scala-ut-action/action.yml'
              - 'python/ppml/**'
              - 'python/dllib/**'
              - '.github/actions/ppml/**'
              
            orca-pytest:
              - 'python/orca/src/**'
              - 'python/orca/dev/**'
              - 'python/orca/test/**'
              - 'python/dllib/src/**'
              - 'scala/orca/pom.xml'
              - 'scala/dllib/pom.xml'
              - '.github/actions/orca/**'
              - 'python/dev/**'

            orca-pytest-openvino:
              - 'python/orca/src/bigdl/orca/learn/openvino/**'
              - 'python/dllib/src/**'
              - 'python/orca/dev/test/**'
              - '.github/actions/orca/**'
              - 'python/dev/**'
              
            orca-tutorial:
              - 'python/orca/src/**'
              - 'python/orca/dev/**'
              - 'python/orca/tutorial/**'
              - 'python/dllib/src/**'
              - 'scala/orca/pom.xml'
              - 'scala/dllib/pom.xml'
              - '.github/actions/orca/**'
              - 'python/dev/**'
              
            orca-example:
              - 'python/orca/src/**'
              - 'python/orca/example/**'
              - 'python/orca/dev/**'
              - 'python/dllib/src/**'
              - 'scala/orca/pom.xml'
              - 'scala/dllib/pom.xml'
              - '.github/actions/orca/**'
              - 'python/dev/**'

  Friesian-Scala-UT:
    # needs: changes
    # if: ${{ needs.changes.outputs.friesian-pytest == 'true' }}
    runs-on: [ self-hosted, ubuntu-20.04-lts, CLX, AVX512, Ettenmoors ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up maven
        uses: ./.github/actions/maven-setup-action
      - name: mvn dependency:tree
        shell: bash
        run: |
          mvn dependency:tree --file scala/pom.xml

 
