# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Nightly Build PyPI Publish Python Sourceforge

on:
  #release:
   # types: [published]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 15 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: [self-hosted,alpha,Esgaroth,ubuntu-20.04-lts]
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.2

    - name: Set up Maven Settings
      uses: s4u/maven-settings-action@v2.6.0
      with:
        sonatypeSnapshots: true
        apacheSnapshots: true
        servers: |
          [{
            "id": "central",
            "configuration": {
              "httpConfiguration": {
                "all": {
                  "connectionTimeout": "3600000",
                  "readTimeout": "3600000"
                  }
                }
              }
          }]
        mirrors: '[{"id": "ardaNexus", "name": "ardaNexus", "mirrorOf": "*", "url": "${NEXUS_URL}" }]'

    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install wheel
        pip install twine
    - name: Build package
      #run: python -m build
      run: |
        export TIMESTAMP=`date '+%Y%m%d'`
        export PYPI_VERSION=2.1.0
        nb_version=${PYPI_VERSION}b${TIMESTAMP}
        echo ${nb_version}
        apt-get update
        apt-get install sshpass
        ## linux ##
        bash python/dev/release_default_linux_spark246.sh ${nb_version} false false
 
        # upload
        sshpass -p 'abcd1234!@#$QWER' \
        scp ./python/dllib/src/dist/bigdl_dllib*-py3-none-manylinux1_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/dllib-py

        sshpass -p 'abcd1234!@#$QWER' \
        scp ./python/orca/src/dist/bigdl_orca*-py3-none-manylinux1_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/orca-py

        sshpass -p 'abcd1234!@#$QWER' \
        scp ./python/friesian/src/dist/bigdl_friesian*-py3-none-manylinux1_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/friesian-py

        sshpass -p 'abcd1234!@#$QWER' \
        scp ./python/chronos/src/dist/bigdl_chronos*-py3-none-manylinux1_x86_64.whl \
        intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/chronos-py

        #sshpass -p 'abcd1234!@#$QWER' \
        #scp ./python/serving/src/dist/bigdl_serving*-py2.py3-none-any.whl \
        #intelanalytics@frs.sourceforge.net:/home/frs/project/analytics-zoo/cluster-serving-py


