name: Scala Test With Spark3

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'scala/**'
      - '.github/workflows/scalatest-spark3.yml'
  schedule:
    - cron: '0 15 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.2

    - name: Set up Maven Settings
      uses: s4u/maven-settings-action@v2.6.0
      with:
        sonatypeSnapshots: true
        apacheSnapshots: true
        servers: |
          [{
            "id": "central",
            "configuration": {
              "httpConfiguration": {
                "all": {
                  "connectionTimeout": "3600000",
                  "readTimeout": "3600000"
                  }
                }
              }
          }]
        mirrors: '[{"id": "ardaNexus", "name": "ardaNexus", "mirrorOf": "*", "url": "${NEXUS_URL}" }]'


    - name: Run tests
      run: |
          export SPARK_LOCAL_HOSTNAME=localhost
          export KERAS_BACKEND=tensorflow
          cd scala
          #mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.optim" test -P spark_3.x -Dspark.version=3.1.2 
          #mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.models" test -P spark_3.x -Dspark.version=3.1.2 
          #mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.estimator" test -P spark_3.x -Dspark.version=3.1.2  
          #mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.nnframes" test -P spark_3.x -Dspark.version=3.1.2 
          #need python requirements
          #mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.keras" test -P spark_3.x -Dspark.version=3.1.2 
          mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.nn.mkldnn" test -P spark_3.x -Dspark.version=3.1.2 
          #mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.feature" test -P spark_3.x -Dspark.version=3.1.2 
          #mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.utils.intermediate" test -P spark_3.x -Dspark.version=3.1.2 
          #mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.utils.tf" test -P spark_3.x -Dspark.version=3.1.2 
          #mvn "-DwildcardSuites=com.intel.analytics.bigdl.dllib.utils.python.api" test -P spark_3.x -Dspark.version=3.1.2 
