name: Scanner-snyk-docker
on:
  #pull_request:
    #branchs: [ main ]

  workflow_dispatch:
    inputs:
      snyk_apitoken:
        description: 'Snyk token'
        required: false
        type: string        
        default: 'monitor'
      snyk_org:
        description: 'Enter synk org: (eg- iags_mlp)'
        required: true
        type: string
        default: 'iags_mlp'
      snyk_image:
        description: 'snyk image'
        required: true
        type: string
        default: 'intelanalytics/bigdl-k8s:latest'

jobs:
  snyk-scan:
    runs-on: [self-hosted, SDL]
    steps:
    - uses: actions/checkout@v3
    - name: set env
      run: |
        echo "SNYK_APITOKEN=${{ github.event.inputs.snyk_apitoken }}"
        echo "IMAGE=${{ github.event.inputs.snyk_image }}"
        echo "SNYK_ORG=${{ github.event.inputs.snyk_org }}"
    - name: "Auth Synk"
      run: |
        snyk auth -d $SNYK_APITOKEN
    - name: "snyk docker"
      run: |
        snyk monitor --docker $IMAGE --api=${SNYK_APITOKEN} --org=${SNYK_ORG}
