name: Scanner-Snyk 
on:
  pull_request:
    branchs: [ main ]

  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Scan type for Snyk'
        required: false
        type: string        
        default: 'monitor'
      snyk_org:
        description: 'Enter synk org: (eg- iags_mlp)'
        required: true
        type: string
        default: 'iags_mlp'
    secrets:
      SNYK_API_TOKEN:
        description: 'Enter Snyk Api Token:'
        required: true

jobs:
  snyk-scan:
    runs-on: [self-hosted, SDL]
    steps:
    - uses: actions/checkout@v3
    - name: "Auth Synk"
      run: |
        #snyk -d auth ${{ secrets.SNYK_API_TOKEN }}
        export SNYK_APITOKEN="89bf9e74-d7ce-4b3b-92c3-2e7cce85bf52"
        snyk auth -d $SNYK_APITOKEN
    - name: "run Snyk test scan"
      env: 
          no_proxy: snyk.devtools.intel.com, intel.com
      run: |
        cd scala
        snyk monitor --all-projects
        cd -
