name: Scanner-virus
on:
  pull_request:
    branchs: [ main ]

jobs:
  snyk-scan:
    runs-on: [self-hosted, SDL]
    steps:
    - uses: actions/checkout@v3
    - name: "virus-malware-scanning"
      run: |
        uvscan --RPTOBJECTS --RECURSIVE --UNZIP --HTML=scan-report.html --LOUD --SUMMARY --ANALYZE --PANALYZE .
