name: stable-diffusion-win
on:
#   pull_request:
#     branchs: [ main ]
  pull_request_target:
    branchs: [ main ]
  schedule:
    - cron: '0 3 * * *' # GMT time, 3:00 GMT == 3:00 China Everyday
  workflow_dispatch:

jobs:
  stable-diffusion-win:
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]
    steps:
      - name: Download log
        run: |
          wget ftp://10.112.231.51:8821/stable-diffusion/ui-test.log --ftp-user=${{ secrets.FTP_USERNAME }} --ftp-password=${{ secrets.FTP_PASSWORD }}
          cat ui-test.log
          rm ui-test.log
